### ISSUE TITLE
Can it go with v22

### ISSUE THREAD

**Issue by abhinav272** [henrytao-me/smooth-app-bar-layout#100]
I have a limitation to not go above v22.
I need to implement the collpasing toolbar that appears (smoothly) when user flings the recyclerview.
Can you help...???

**Comment by henrytao-me** [comment]
I am sorry @abhinav272 
There are huge APIs changed in v23 that are not backward compatible with v22. 

I did have some releases for v22.x. You can try `1.0.5`. See full list here. https://bintray.com/henrytao-me/maven/smooth-app-bar-layout/view

Let me know if it helps.

**Comment by abhinav272** [comment]
Thanks for prompt reply...!!
I already tried using 1.0.5v but the BaseBehavior class is using DragCallback object which is basically a subclass of AppBarLayout.Behavior v23.1.1

So no Luck :(

**Comment by henrytao-me** [comment]
Then, please try other older versions.

**Comment by domsu** [comment]
@henrytao-me Do you plan to release version that supports 23.3.0 of android support library?

**Comment by henrytao-me** [comment]
I will look into it.

**Comment by henrytao-me** [comment]
It's supported. Please check https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/CHANGES.md
