### ISSUE TITLE
minSdkVersion is 11?

### ISSUE THREAD

**Issue by mchun** [henrytao-me/smooth-app-bar-layout#101]
Thanks for the great library, but I encountered the following error when compiling...

Error:Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : uses-sdk:minSdkVersion 9 cannot be smaller than version 11 declared in library [me.henrytao:smooth-app-bar-layout:23.2.1] 
>     Suggestion: use tools:overrideLibrary="me.henrytao.smoothappbarlayout" to force usage

Is it save to override and use it in android 2.3?

**Comment by henrytao-me** [comment]
Hi @mchun 

MinSdkVersion for SmoothAppBarLayout is 11. Look like there is no issue with version 9 but you have to test it out. I thought version 11 is standard min sdk for now. No?

Cheers, 
Henry

**Comment by mchun** [comment]
Well... millions of toxic e-waste are created every year due to planned-obsolescence by the big cooperations.
I just try to be a responsible developer and support as old as I can.

**Comment by henrytao-me** [comment]
Which version of SmoothAppBarLayout are you using?
