### ISSUE TITLE
Quick Return toolbar pops down unexpectedly with changing view sizes in recycler view

### ISSUE THREAD

**Issue by Jeffphuang** [henrytao-me/smooth-app-bar-layout#108]
If flags enterAlways|enterAlwaysCollapsed (quick return) is enabled with a recycler view that has dynamic sizes for view holders, the toolbar will bounce back once scrolled past the collapsing toolbar.

Steps to Reproduce (Tested on LG Nexus 5X on Android 6.0.1):
1. Download Demo App
2. Launch the SmoothAppBarLayout QuickReturn Demo
3. Scroll until the recycler view holder Line 1 is aligned with the top of the screen (the toolbar should be completely collapsed at this point)
4. expand/shrink recycler viewholder line 4 by tapping on it

Result: the toolbar comes in and out of view. This does not occur in the default material design implementation from google.

**Comment by henrytao-me** [comment]
Hi @Jeffhuang1 

I tested it on my Nexus 5X. It doesn't happen. Can you take a video on your end? 

Cheers, 
Henry

**Comment by Jeffphuang** [comment]
@henrytao-me Heres the video on my Nexus 5X
https://youtu.be/A4-wA3lJX_I

**Comment by henrytao-me** [comment]
I got it. Working on the fix tonight. Thanks.

**Comment by henrytao-me** [comment]
@Jeffhuang1 Please check latest build on master. 

Thanks.
