### ISSUE TITLE
NestedScrollView/CustomNestedScrollView whitespace issue with non-expanded toolbar on orientation change

### ISSUE THREAD

**Issue by drinkthestars** [henrytao-me/smooth-app-bar-layout#109]
In the sample app, for both the `NestedScrollView` and the `CustomNestedScrollView` demos, while changing orientation (after having scrolled a little), the extra spacing thats placed in the `NestedScrollView`/`CustomNestedScrollView` appears to show up out from underneath the toolbar. The toolbar then jumps to the expanded state when you start to scroll.

Steps to repro:
1. In the `NestedScrollView`/`CustomNestedScrollView` scroll a little to have the toolbar in a non-expanded state
2. Rotate the device
3. Note how the whitespace (that is used to make space for the header/toolbar) shows up
4. Start to scroll in the `NestedScrollView`/`CustomNestedScrollView` and note how the toolbar snaps to an expanded state

It seems like even though the offset is preserved throughout the orientation change, the  `NestedScrollView`/`CustomNestedScrollView`'s scroll position doesn't get preserved?
### Screenshots

<img width="209" alt="screen shot 2016-05-25 at 12 29 12 pm" src="https://cloud.githubusercontent.com/assets/2978958/15553545/6435674e-2274-11e6-9530-569ecb74dcd2.png">
<img width="401" alt="screen shot 2016-05-25 at 12 30 38 pm" src="https://cloud.githubusercontent.com/assets/2978958/15553582/87d7b792-2274-11e6-9b23-4e3a393b04f9.png">

**Comment by henrytao-me** [comment]
I thought I fixed it before. Let me look into it.

**Comment by henrytao-me** [comment]
Hi @drinkthestars 

It's happened because I haven't set `id` for `NestedScrollView`. Without `id`, android won't do `saveInstanceStates` on `orientationChanged`.

Please check my commit above. 

Thanks, 
Henry
