### ISSUE TITLE
Example with transparent statusbar

### ISSUE THREAD

**Issue by petersnoopy** [henrytao-me/smooth-app-bar-layout#11]
Hi, it would be great to see an example of a parallax header with a transparent statusbar.

**Comment by henrytao-me** [comment]
Sure. I will add it in the next release. I will ping you when it's ready.

**Comment by henrytao-me** [comment]
Sweeeeeeeet! version `0.1.5` is out. Check it out. ViewPager support + Inbox App and Google Play App Detail samples included. #2

**Comment by petersnoopy** [comment]
Thank you, I will try...

**Comment by akbarnwal** [comment]
Thanks Henrytao :)
Really "Smooth ViewPager Parallax" is very smooth compare to native one.

Can we get "Smooth ViewPager Parallax" with DrawerLayout ? I am not able to get any example with it in Google. If you have same example please share link.

Thanks again.

Thanks
Anil

**Comment by henrytao-me** [comment]
I think you can combine my top 2 examples: inbox and google play.

**Comment by henrytao-me** [comment]
Let me post some examples later. ;)

**Comment by henrytao-me** [comment]
Hi @nomad609, 

Check it out. I added 2 more examples in version `0.1.8`.

**Comment by akbarnwal** [comment]
Thanks Henrytao :)

You are very fast, really appreciates your help.

I will check and let you know.

Thanks,
Anil

**Comment by henrytao-me** [comment]
Cool. Grab me some beer then. ;) Cheers!
