### ISSUE TITLE
Elevation on Toolbar

### ISSUE THREAD

**Issue by nominalista** [henrytao-me/smooth-app-bar-layout#110]
Is it possible to add elevation to Toolbar, but only when it is collapsed? Of course, when it is expanded, I'd like to hide this elevation.

**Comment by henrytao-me** [comment]
I think it's possible. I will send you a demo soon.

**Comment by nominalista** [comment]
Thank you very much. I'm waiting for demo.

**Comment by henrytao-me** [comment]
Hi @Nominalista 
Please checkout this branch and try it. https://github.com/henrytao-me/smooth-app-bar-layout/tree/issue-110. I think it's a default implementation of Toolbar.

**Comment by nominalista** [comment]
Why I can't see elevation in QuickReturn example ?

**Comment by henrytao-me** [comment]
What device are you using? Elevation is only supported on API 21 and above

**Comment by nominalista** [comment]
Htc One M8 with API 23, I also can't see this on emulator with API 23. 

<img width="298" alt="screen shot 2016-05-28 at 23 58 10" src="https://cloud.githubusercontent.com/assets/9215552/15630202/143235ce-2530-11e6-9024-7710adda5d68.png">

**Comment by henrytao-me** [comment]
Hi @Nominalista 

What APK is it?

**Comment by henrytao-me** [comment]
Did you check out the branch I sent you and run the build?

**Comment by henrytao-me** [comment]
I merged it to master. You can run again on master now.

**Comment by nominalista** [comment]
Can you show me screenshot with elevation in QuickReturn example ? Cause still when I fetched master can't see elevation.

**Comment by henrytao-me** [comment]
For QuickReturn example, the elevation is displayed under statusbar. Check out these screenshots below
https://drive.google.com/file/d/0B5HntpVe6CemZjRQYVg3U0hTWTQ/view?usp=sharing
https://drive.google.com/file/d/0B5HntpVe6CemSHctSEpZeks5cWc/view?usp=sharing

It seems like you want to have elevation showed when it returns. If so, I am not sure it's possible. Please confirm and I will look into it.

**Comment by nominalista** [comment]
Yes, that's why I created issue, because I wasn't sure if it's possible too. Please look into it and thank you for your time spend on it.
