### ISSUE TITLE
smooth app bar layout collapses without scrolling header

### ISSUE THREAD

**Issue by suhaibroomy** [henrytao-me/smooth-app-bar-layout#117]
![screenshot_20160704-021606](https://cloud.githubusercontent.com/assets/12771866/16547502/96cf3454-418d-11e6-8353-177769177a56.png)
![screenshot_20160704-021621](https://cloud.githubusercontent.com/assets/12771866/16547503/96fd6d7e-418d-11e6-9187-972162b42e4d.png)

This happens every time when i insert an item. help me debug this

**Comment by henrytao-me** [comment]
Let me look into it

**Comment by suhaibroomy** [comment]
i can provide you with logs if you want. or we can debug over teamviewer. let me know

**Comment by henrytao-me** [comment]
Please provide more information about your current setup. Ex: what version of SmoothAppBarLayout, AppCompat version, support design version, device name, OS version? Thanks.

**Comment by suhaibroomy** [comment]
smoothAppBarLayout - 3.0.0 (tested with 23.3.0 as well)
AppCompat - 24.0.0 (tested with 23.3.0 as well)
Support Design - 24.0.0 (tested with 23.3.0 as well)
device - tested with samsung s6, s5, nexus 5x and some other low end devices
os version - tested on marshmallow and lollipop

**Comment by henrytao-me** [comment]
Hi @suhaibroomy 

I have a few questions: 
1. Are you using Fragment for the list? 
2. If so, did you initiate Fragment properly? Ex: only create new fragment in `activity.onCreate` when `savedInstanceState` is null. 
3. If you data is loaded async, you can call `smoothAppBarLayout.syncOffset(your_recycler_view_current_vertical_offset)` onResume
4. Did you turn on `Don't keep activities` flag in `Developer options`? If yes, it's the root cause. State of SmoothAppBarLayout is restored properly but RecyclerView in Fragment doesn't.

**Comment by henrytao-me** [comment]
In the meantime, you can fix this issue by following code if you are using RxJava (If not, do similar thing with handler). I will review the library internally this weekend. Thanks. 

``` java
  @Override
  protected void onResume() {
    super.onResume();
    Observable.timer(200, TimeUnit.MILLISECONDS).observeOn(AndroidSchedulers.mainThread()).subscribe(l -> {
      vSmoothAppBarLayout.syncOffset(your_recycler_view_current_verftical_offset);
    });
  }
```

**Comment by suhaibroomy** [comment]
1. yes i am using a fragment for list
2. no i didn't initiate it properly but i don't think thats the issue. because it happens every time regardless of activity state
3. no i didn't turn it on

My structure - Activity contains appbar , fragment A(list) and fragment B(bottom sheet).
fragment B(bottom sheet) contains a child fragment and whenever i try to update fragment A from this fragment it goes into this state.

**Comment by suhaibroomy** [comment]
thanks...it wasn't happening due to activity getting killed. fixed my code using your solution on the scenarios it was happening rather than onresume

**Comment by henrytao-me** [comment]
Thanks @suhaibroomy 

I am working on v4 which potential smoother and simpler to use. It may take a look of twist on TouchEvent system. I will let you know when it's rolled out. 

Cheers, 
Henry

**Comment by suhaibroomy** [comment]
oh thats great news. will be waiting for it. cheers

**Comment by henrytao-me** [comment]
Hi @suhaibroomy 

Please try out latest version. Hopefully it's resolved your issue. Please reopen this issue if you need further assist.
