### ISSUE TITLE
how to use this lib with scrollview?

### ISSUE THREAD

**Issue by bahacan19** [henrytao-me/smooth-app-bar-layout#12]
Is there any sample to use this via scroll view? How to add header to scrollview?
Thanks

**Comment by henrytao-me** [comment]
Hi @bahacan19, 
I already added samples for NestedScrollView. Check out some examples in version 0.1.3

**Comment by henrytao-me** [comment]
I have 2 examples: 
- One uses `android.support.v4.widget.NestedScrollView` => Scrolling is handled by `getViewTreeObserver()` which works quite well.
- One uses `me.henrytao.smoothappbarlayout.widget.NestedScrollView` => Scrolling is handled by custom scroll event which is more accurate.
