### ISSUE TITLE
Prevent RecyclerView from scrolling under AppBarLayout before AppBarLayout is collapsed

### ISSUE THREAD

**Issue by xpbtmusic** [henrytao-me/smooth-app-bar-layout#121]
Prevent RecyclerView from scrolling under AppBarLayout before AppBarLayout is collapsed

**Comment by henrytao-me** [comment]
Can you describe more about this issue?

**Comment by xpbtmusic** [comment]
When I touch slide up, appbar are folding , recycleView should stop scrolling until it slide to the top, recycleView can slide and scroll.

**Comment by xpbtmusic** [comment]
Hi, there's another problem, DragTopLayout added PullToRefresh, if the topView has  two rows of the button with pictures at drawableTop can not slide.

**Comment by mark-dlc** [comment]
Sounds to me like you are using `app:layout_behavior="@string/appbar_scrolling_view_behavior"` on your scrolling view. Could that be?

**Comment by henrytao-me** [comment]
Thanks for helping @mark-dlc

**Comment by henrytao-me** [comment]
@mark-dlc  Does SmoothAppBarLayout work on your projects? Do you need any help?

**Comment by mark-dlc** [comment]
@henrytao-me SmoothAppBarLayout is the only solution so far that fixes the smooth scrolling issue for me. I still had/have to dot some i's and cross some t's (had this issue: https://github.com/henrytao-me/smooth-app-bar-layout/issues/92, but was able to work around that with manually added margin) but I'm getting there. Wasn't expecting this commercial-class support on an open source project, you're truly doing a great job!

**Comment by henrytao-me** [comment]
Thanks @mark-dlc. I will keep contribute to community.
