### ISSUE TITLE
scroll not work when setting LayoutManager VERTICAL in recyclerview 

### ISSUE THREAD

**Issue by narinbsru** [henrytao-me/smooth-app-bar-layout#125]
`RecyclerView.LayoutManager mLayoutManager = new GridLayoutManager(getActivity().getApplicationContext(), 3, GridLayoutManager.VERTICAL, false);
`

**Comment by henrytao-me** [comment]
Can you send me the apk? I checked and it worked on my side. Also, what version of AppCompat and Support Design are you using?

**Comment by henrytao-me** [comment]
Please let me know if you need further assist. For now, I will close this issue.
