### ISSUE TITLE
Failed to resolve: me.henrytao:smooth-app-bar-layout:23.4.0.*

### ISSUE THREAD

**Issue by ln206** [henrytao-me/smooth-app-bar-layout#128]
Hello there,

I'm trying to include smooth-app-bar-layout in my test project. But i'm getting this error:

`Error:Failed to resolve: me.henrytao:smooth-app-bar-layout:23.4.0.*
<a href="openFile:C:/Users/Long Nguyen/Desktop/MyApplication/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>`

Here's my build.gradle file:

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "24.0.0"

```
defaultConfig {
    applicationId "com.what.yeah.myapplication"
    minSdkVersion 15
    targetSdkVersion 23
    versionCode 1
    versionName "1.0"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

repositories {
    jcenter()
}

dependencies {
    compile fileTree(dir: 'libs', include: ['_.jar'])
    testCompile 'junit:junit:4.12'
    compile "com.android.support:design:23.4.0"
    compile "com.android.support:appcompat-v7:23.4.0"
    compile "me.henrytao:smooth-app-bar-layout:23.4.0._"
}
`

Please help me solve this problem. Thanks.

**Comment by henrytao-me** [comment]
Hi @ln206 

Please try `compile "me.henrytao:smooth-app-bar-layout:23.4.0.1"`. Thanks.
