### ISSUE TITLE
Added support for SwipeRefreshLayout

### ISSUE THREAD

**Issue by StanKocken** [henrytao-me/smooth-app-bar-layout#13]
Currently if we are using a SwipeRefreshLayout, our SmoothAppBarLayout is not moving. It could be cool to add this support.

What do you think?

**Comment by henrytao-me** [comment]
Let me check and make some examples. It should work!

**Comment by StanKocken** [comment]
Ok, I was not able to make it work.

Into SmoothAppBarLayout, init(), you have a case with RecyclerView, ViewPager, NestedScrollView (which is not SwipeRefreshLayout) but nothing for the SwipeRL. So it will fall into "target.getViewTreeObserver().addOnScrollChangedListener()".

PS: I wanted to try to fix it during my test of your library but it's kind of hard to have your lib working as a submodule due to the "rootProject.ext.XXX" references into build.gradle. But I didn't want to open an issue on that because it's not the main purpose of your library.

**Comment by henrytao-me** [comment]
Okie. I am about pushing new version. ;)

**Comment by henrytao-me** [comment]
Hi @StanKocken 
Checkout v0.1.4. You have to wait few hours to see new version on Google Play or you can build it yourself. 

For second question, if you want to run this project as submodule, you can apply the config file to your project gradle. It's something like this: `apply from: "<submodule directory>/smooth-app-bar-layout/config.gradle"`

**Comment by StanKocken** [comment]
Thanks it works with SwipeRefreshLayout now.

**Comment by deep-154** [comment]
Hi, I know this issue is closed, but SwipeRefreshLayout is not working. I am using 0.2.0 version of your lib. 
The main issue is since my collapsingToolbar does not have fixed size, I am providing the padding to SwipeRefreshLayout at runtime. I have also setClipToPadding(false). 
Any help will be greatly appreciated.

Thanks
