### ISSUE TITLE
android:minHeight   

### ISSUE THREAD

**Issue by cococa** [henrytao-me/smooth-app-bar-layout#131]
Remember to set android:minHeight for me.henrytao.smoothappbarlayout.SmoothAppBarLayout in layout file if you use ViewPager.

how to calculate minHeight value？it's also 48p？

**Comment by henrytao-me** [comment]
Hi @cococa 

`minHeight` is only needed if you want to use with ViewPager. Normally, it's 48dp unless you want it bigger

**Comment by cococa** [comment]
@henrytao-me  thanks！
