### ISSUE TITLE
Failed to sync gradle project

### ISSUE THREAD

**Issue by sgaikar1** [henrytao-me/smooth-app-bar-layout#133]
@henrytao-me i am unable to sync my gradle with your repository.
my design support and appcompat support version is 24.1.1

**Comment by henrytao-me** [comment]
Hi @sgaikar1 

Can you send your gradle file here? Also, please check if you uncheck offline work in Gradle settings (Android Studio preferences).

**Comment by sgaikar1** [comment]
@henrytao-me i got issue which is allready in your closed topics.. i need to use your library with version 24.1.0.0

**Comment by henrytao-me** [comment]
I see. You can also try this build 

`compile "me.henrytao:smooth-app-bar-layout:24.1.1.0"`

**Comment by sgaikar1** [comment]
thanx i will update it in my gradle.. and your help is much apreciated.. thank you :)
