### ISSUE TITLE
Avoid onRestoreInstanceState

### ISSUE THREAD

**Issue by Ozuan** [henrytao-me/smooth-app-bar-layout#137]
HI @henrytao-me 

I don't want to save my layout after rotation, the problem is that after the ID is set on SmootAppBarlayout the system will automatically save its Instance State in a Bundle object. (I need the ID here for other methods)

Simple question:  How to override that so It doesn't save the Instance state?

Regards.

**Comment by henrytao-me** [comment]
Hi @Ozuan 

The output of disabling `onRestoreInstanceState` is: always scroll to the top after rotating, isn't it? 
If yes, you can try something like this

``` java

  @Override
  public void onResume() {
    super.onResume();       
    recyclerView.getViewTreeObserver().addOnGlobalLayoutListener(this);
  }

  @Override
  public void onGlobalLayout() {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
      recyclerView.getViewTreeObserver().removeOnGlobalLayoutListener(this);
    } else {
      try {
          recyclerView.getViewTreeObserver().removeGlobalOnLayoutListener(this);
      } catch (Exception ignore) {
      }
    }
    recyclerView.scrollToPosition(0);
    smoothAppBarLayout.syncOffset(0);
  }
```

The idea is: calling syncOffset(0) to reset SmoothAppBarLayout. You may need to make sure the scrolling position of RecyclerView or NestedScrollView is correct after rotating.
