### ISSUE TITLE
App bar hides unexpectedly when image loaded

### ISSUE THREAD

**Issue by teddychoi** [henrytao-me/smooth-app-bar-layout#139]
Hi.

When 'Picasso' loads images, app bar hides unexpectedly.

Video:
https://drive.google.com/file/d/0B8dZDvlWYJm1TWtmYVBIay0wblU/view

Full source code:
https://github.com/teddychoi/Curzytagram

Is there something I missed?

**Comment by henrytao-me** [comment]
Interesting. I am checking your repo.

**Comment by henrytao-me** [comment]
Hi @teddychoi 

Please try `24.2.0.2`. It's fixed. Thanks for reporting this issue with sample project. 🙇
