### ISSUE TITLE
Content appears behind AppBarLayout

### ISSUE THREAD

**Issue by MrLepage** [henrytao-me/smooth-app-bar-layout#143]
Using version 24.2.1.0, NestedScrollView content appears behind AppBarLayout

![zeroltexxmmb29kalepage09192016154835](https://cloud.githubusercontent.com/assets/18703480/18634296/a4785fce-7e80-11e6-81ae-00fdfba30ce4.png)

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/main_content"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v4.widget.NestedScrollView
        android:id="@+id/nested_scroll_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout...>
    </android.support.v4.widget.NestedScrollView>

    <me.henrytao.smoothappbarlayout.SmoothAppBarLayout
        android:id="@+id/app_bar_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/colorPrimary"
        android:minHeight="?attr/actionBarSize">

        <android.support.design.widget.CollapsingToolbarLayout
            android:id="@+id/collapsing_toolbar_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_scrollFlags="scroll|exitUntilCollapsed">

            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:layout_collapseMode="pin" />

            <LinearLayout...>
        </android.support.design.widget.CollapsingToolbarLayout>
    </me.henrytao.smoothappbarlayout.SmoothAppBarLayout>
</android.support.design.widget.CoordinatorLayout>
```

**Comment by henrytao-me** [comment]
Please set header padding for NestedScrollView (same height as SmoothAppBarLayout's height)

**Comment by MrLepage** [comment]
The library isn't supposed to do this itself ? I've used it in another project some time ago without having to set this padding manually. (maybe I am wrong)

Thanks for your quick answer

**Comment by henrytao-me** [comment]
Hi @UNCVR 

Due to the approach of SmoothAppBarLayout, you need to handle header view. It's tricky to do it in the library. In original AppBarLayout, you don't have to care about header view but it causes another issues.

**Comment by roman-ku** [comment]
I had the same issue, very annoying. Soo glad I found this post.

Here is how you do that:

    <android.support.design.widget.CoordinatorLayout

        <android.support.v4.widget.NestedScrollView
            ...
            android:paddingTop="XXXdp"
            android:clipToPadding="false"
            ...


        <me.henrytao.smoothappbarlayout.SmoothAppBarLayout
            ...
            android:layout_height="XXXdp"
            ...

    </android.support.design.widget.CoordinatorLayout>

**Comment by henrytao-me** [comment]
Thanks @roman-ku. I am glad that you can make it work.

**Comment by roman-ku** [comment]
Maybe add a note to the read me?
