### ISSUE TITLE
Header issue

### ISSUE THREAD

**Issue by sumitsahu2207** [henrytao-me/smooth-app-bar-layout#147]
Hi,

I'm facing issue while adding header to recylcerview.
When I'm scrolling recyclerview, it adds some space between recyclerview items.
Please suggest, how should I resolve this issue.

Best Regards,
Sumit

**Comment by henrytao-me** [comment]
Hi @sumitsahu2207 

Please provide some screenshots or video about the issue. Thanks.

**Comment by sumitsahu2207** [comment]
Hi,

Please find attached xml layouts and screenshots

[activity_main.txt](https://github.com/henrytao-me/smooth-app-bar-layout/files/502623/activity_main.txt)
[content_activity_main.txt](https://github.com/henrytao-me/smooth-app-bar-layout/files/502624/content_activity_main.txt)

![screenshot_2016-09-30-15-23-08](https://cloud.githubusercontent.com/assets/19974192/18988012/51ffcc14-8722-11e6-9386-d0c4d0877952.png)
![screenshot_2016-09-30-15-23-02](https://cloud.githubusercontent.com/assets/19974192/18988013/525fe57c-8722-11e6-8f5c-16df7a7a9560.png)
![screenshot_2016-09-30-15-22-56](https://cloud.githubusercontent.com/assets/19974192/18988014/528d31e4-8722-11e6-958d-2a5fdf118ee6.png)

**Comment by henrytao-me** [comment]
Hi @sumitsahu2207 

If you use RecyclerView, the HeaderView should be the first item in RecyclerView adapter. You have 2 options to do that: use viewType to setup header item or use wrapper adapter approach like this https://github.com/henrytao-me/recyclerview-multistate-section-endless-adapter

Cheers, 
Henry
