### ISSUE TITLE
Can it support pulltorefreshLayout

### ISSUE THREAD

**Issue by asker517** [henrytao-me/smooth-app-bar-layout#15]
Well, i run ViewPager + Tabs + ToolBar example .. worked nice .
but all ViewPager content is RecyclerView with a header to hold the position.
I just try to use [Android-PullToRefresh](https://github.com/chrisbanes/Android-PullToRefresh) or [android-Ultra-Pull-To-Refresh](https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh) ..if add a header to RecyclerView it will effect the refreshLayout position..
  However,google support design package appbarlayout support it all well ..just some scrolling tricks..
Can this library will support the widget?

**Comment by henrytao-me** [comment]
Hi @asker517, 

Currently, `smoot-app-bar-layout` supports `SwipeRefreshLayout` from AppCompat. Checkout this thread #13 and version `0.1.4`. 

Let's me know if you really want to support other PullToRefresh libraries.

**Comment by henrytao-me** [comment]
You said you run ViewPager + Tabs + ToolBar already. Is it a custom code? If so, would you like to send a PR? 

I just release version 0.1.4 yesterday which has major improvements and some sample code for ViewPager but they still need to be tweaked before releasing.

**Comment by asker517** [comment]
@henrytao-me 
No,I just run version 0.1.4 ViewPager + Tabs + ToolBar Example :smile: 

I use other PullToRefresh library because  it's easy to custom refreshing layouts and animations ..
maybe just a case ...but help needed ..thanks for your reply rapidly.

**Comment by henrytao-me** [comment]
Sweet. I will take a look at other PullToRefresh libraries. However, checkout `getScrollTarget(View target)` method in `BaseBehavior`, if you have any idea to make it widely supports other PullToRefresh, feel free to send a PR. Happy coding.

**Comment by henrytao-me** [comment]
Hi @asker517 

`v1.0.2` is out. You can try [smoothAppBarLayout. setScrollTargetCallback(...)](https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/smooth-app-bar-layout%2Fsrc%2Fmain%2Fjava%2Fme%2Fhenrytao%2Fsmoothappbarlayout%2FSmoothAppBarLayout.java#L126)

Let me know if you need more help.

**Comment by asker517** [comment]
OK I will try it later . thanks

Hi @asker517 https://github.com/asker517

v1.0.2 is out. You can try smoothAppBarLayout. setScrollTargetCallback(...)
https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/smooth-app-bar-layout%2Fsrc%2Fmain%2Fjava%2Fme%2Fhenrytao%2Fsmoothappbarlayout%2FSmoothAppBarLayout.java#L126

Let me know if you need more help.
