### ISSUE TITLE
RecylerView inside CollapsingToolbarLayout

### ISSUE THREAD

**Issue by sach185** [henrytao-me/smooth-app-bar-layout#150]
My requirement is that I need a Recycler view inside my collapsing toolbar.

Layout : 

```
<CoordinatorLayout>
<RecyclerView>
<SmoothAppBar>
<CollapsingToolbarLayout>
**<RecyclerView/>**
</CollapsingToolbarLayout>
<TabLayout>
</SmoothAppBar>
</CoordinatorLayout>
```

The issue I face now is that there is no scroll on Appbar.
Is there any way to implement this?

**Comment by henrytao-me** [comment]
Hi @sach185 

In your second RecyclerView (the one is **). Please try `recyclerView.setNestedScrollingEnabled(false);`

I hope it help.

Cheers, 
Henry

**Comment by henrytao-me** [comment]
I will close this issue for now. Let me know if you need further assist. Thanks.
