### ISSUE TITLE
Demo For CollapsingToolbar

### ISSUE THREAD

**Issue by petitTrung** [henrytao-me/smooth-app-bar-layout#151]
Hello, thanks for your solution.

Could you put a sample with CollapsingToolbarLayout in which there is an Image like [Cheesesquare by Chrisbanes](https://github.com/chrisbanes/cheesesquare/blob/master/app/src/main/res/layout/activity_detail.xml) please ?

Many thanks.

**Comment by henrytao-me** [comment]
Hi @petitTrung 

I think I have it locally. Give me a second.

**Comment by henrytao-me** [comment]
Hi @petitTrung 

Parallax examples are on master branch now. You can either checkout master or check diff here https://github.com/henrytao-me/smooth-app-bar-layout/pull/152/files

Happy coding.
