### ISSUE TITLE
Horizontal Recyclerview inside an item is causing problem.

### ISSUE THREAD

**Issue by ghost** [henrytao-me/smooth-app-bar-layout#153]
Hi,

Thanks for the library, its been very useful !! I am using a Recyclerview under Appbar layout and I have an Horizontal Recyclerview in one of the cell in parent Recyclerview.  When the first item of that Horizontal Recyclerview is scrolled , the contents in appbar layout appears, when I scroll to third item , it disappears again, and when i come back to first item, it appears again. I want the smoooth appbar to be disabled when I am scrolling Horizontal recyclerview.What can I do?

Thanks.

**Comment by henrytao-me** [comment]
Hi @arjunhegde372 

You found the way right? Btw, set this to your horizontal recycler view `horizontalRecyclerView.setNestedScrollingEnabled(false);`

Cheers, 
Henry
