### ISSUE TITLE
Weird behavior when Image is FullScreen

### ISSUE THREAD

**Issue by petitTrung** [henrytao-me/smooth-app-bar-layout#154]
Hi,

I found a bug when i define Image in FullScreen mode as you can see in this video : 

[Bug Video](https://youtu.be/INWIlbBLFPU)

I have just forked your project and you can refer this bug by this commit : 

[Bug Commit](https://github.com/petitTrung/smooth-app-bar-layout/commit/68f251859dfa46158d6ae705f4525c7ec075b86a)

Could you take a look please.

Thanks

**Comment by henrytao-me** [comment]
Let me check

**Comment by henrytao-me** [comment]
@petitTrung 

Please check my comment.
