### ISSUE TITLE
Can i fix toolbar(always shown) as well?(while using viewpager as well)

### ISSUE THREAD

**Issue by Jude-KIM** [henrytao-me/smooth-app-bar-layout#158]
Hello.
I'm using SmoothAppbarLayout with toolbar and viewpager together.

But i want to make both toolbar and viewpager(tab) fixed when collapsed.
So only the spaces between toolbar and tab are expanded, and both are always shown.

Do you think it's possible?

Oh, by the way, I got build error("can't resolve" error) everytime i tried to add 'compile me.henrytao:smooth-app-bar-layout:24.1.0.*' to my gradle. the version number doesn't matter. with * or not also doesn't matter. Keep showing me build error. 
So i imported all of your library filed to my project. Please see this as well.

Thanks.

**Comment by henrytao-me** [comment]
Hi @Jude-KIM 

It's better if you can show me a screenshot to illustrate with you want to do. I not sure about the issue with `24.1.0.*`. If possible, please try latest version which is `24.2.1.0`. It highly recommends to use fix version instead of `*` to avoid unexpected result. 

Cheers, 
Henry

**Comment by Jude-KIM** [comment]
Hi Henry.

Please check belows.

What i want(Tool bar and tab  are always showing)

```
   collasped                          expanded
```

What smooth-app-bar look like(Tool bar is gone when scroll. But tab is
showing)

```
 collasped​
```

Smoothappbar always hide the tool bar when scrolling down. I want to make
tool bar is always showing, just like tab.

And
'me.henrytao:smooth-app-bar-layout:24.2.1.0'

worked for me. Format like   num.num.num.\*   never worked. You better edit
'readme'.

Thanks.

**Comment by henrytao-me** [comment]
Thanks @Jude-KIM I will check and reply you later. Cheers.

**Comment by henrytao-me** [comment]
README is updated. Thanks for your report.
