### ISSUE TITLE
RecyclerView scrollToPosition doesn't affect app bar initially

### ISSUE THREAD

**Issue by smelfungus** [henrytao-me/smooth-app-bar-layout#174]
Easy reproducing with in-library sample:
SmoothScrollParallaxActivity
After line 91 add:
```
    vRecyclerView.postDelayed(new Runnable() {
      @Override
      public void run() {
        vRecyclerView.smoothScrollToPosition(30);
      }
    }, 2000);
```
RecyclerView will scroll down but app bar won't collapse.
There is also an important note — if any manual interactions with RecyclerView are done before programmatic scroll — it will fire as it should.
Am I missing something? Maybe it is needed to perform some kind of sync on initialization? 
Thank you in advance.

**Comment by henrytao-me** [comment]
Thanks for your feedback. The fix is on this PR https://github.com/henrytao-me/smooth-app-bar-layout/pull/176. I am about deploying to all release versions.

**Comment by henrytao-me** [comment]
Hi @DummyCo 

What support lib version are you using?

**Comment by henrytao-me** [comment]
Please check TAGS section in this repo to see all supported version. Thanks. Let me know if you run into any other issues.

**Comment by smelfungus** [comment]
@henrytao-me, works like a charm now, thank you.
25.1.0 support version is used.

**Comment by henrytao-me** [comment]
Nice @DummyCo
