### ISSUE TITLE
How to Use it in Xamarin.Android

### ISSUE THREAD

**Issue by Kasilingam1230** [henrytao-me/smooth-app-bar-layout#175]
I have tried Java Binding, but no use with that. Kindly specify how to use it Xamarin.Android

**Comment by henrytao-me** [comment]
Hi @Kasilingam1230 

I haven't worked on Xamarin. Not sure how to help you with this. I am sorry.

**Comment by henrytao-me** [comment]
I will close this ticket for now. Sorry about that.
