### ISSUE TITLE
Recycler View with a few items

### ISSUE THREAD

**Issue by shmuelr** [henrytao-me/smooth-app-bar-layout#18]
Hey, 

When the recyclerview has only a few items and does not fill up the screen then the collapsing toolbar does not work. It stays in the expanded state and does not allow the recyclerview to scroll, due to the fact that all of the recycler items are visible onscreen at once.
I verified that with the design support library the toolbar will collapse up even if the recyclerview only has one item.

Any suggestions?

Thank you!

**Comment by henrytao-me** [comment]
Hi,
SupportDesign and SmoothAppBarLayout use different approach. In case all items are onscreen, I think there are no need for scrolling. Do you think so?

**Comment by shmuelr** [comment]
Thanks for the prompt response!
It gets into a weird state when there is one item peeking of the bottom of the screen. Then I am able to scroll it up a tiny bit, but only until the edge of the last item. The collapsing toolbar is then in a collapsed state and does not collapse all the way.

**Comment by henrytao-me** [comment]
Can you send your layout file?

**Comment by shmuelr** [comment]
Here is the layout file - http://pastebin.com/E6NNt75f

I also uploaded a screenshot here - http://www.tiikoni.com/tis/view/?id=3148596
When there are 5 items on my screen (Galaxy Note 4) then the bar collapses half way but no more because the recyclerview is in full view.

**Comment by henrytao-me** [comment]
In your case, I suggest you can: 
- Just remove activity title. Tiny scrolling is not too bad. 
- Or add more `padding-bottom` and use `clipToPadding=false` to make it's always full-scrollable. 

Take a look at Google Contact App. Tiny scrolling is still a pretty good behavior. If you have any other feedback or suggestion, please let me know.
