### ISSUE TITLE
SmoothScroll with ListView

### ISSUE THREAD

**Issue by ayinmursalin** [henrytao-me/smooth-app-bar-layout#182]
i don't ever try Collapsing Toolbar yet, and i need add that thing to my ListView

i have try yours but i see nothing (?)

and i don't know what means you add <RecyclerView> in above of <SmoothAppBarLayout>
i use this smoothappbar for include content_main, which is have <ListView>

i need your guide, thanks..

**Comment by ayinmursalin** [comment]
this is my activity_main.xml

`<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context="com.ayndev.a_time.MainActivity">

    <android.support.v7.widget.RecyclerView
        android:id="@android:id/list"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <me.henrytao.smoothappbarlayout.SmoothAppBarLayout
    android:id="@+id/smooth_app_bar_layout"
    android:layout_width="match_parent"
    android:layout_height="@dimen/app_bar_height">

        <android.support.design.widget.CollapsingToolbarLayout
            android:id="@+id/collapsing_toolbar_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_scrollFlags="scroll|exitUntilCollapsed">

            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                style="@style/AppTheme.AppBarOverlay"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:layout_collapseMode="pin" />

        </android.support.design.widget.CollapsingToolbarLayout>

    </me.henrytao.smoothappbarlayout.SmoothAppBarLayout>

    

</android.support.design.widget.CoordinatorLayout>
`

**Comment by ayinmursalin** [comment]
and this is my code for main_activity.xml

`<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context="com.ayndev.a_time.MainActivity">

    <me.henrytao.smoothappbarlayout.SmoothAppBarLayout
    android:id="@+id/smooth_app_bar_layout"
    android:layout_width="match_parent"
    android:layout_height="@dimen/app_bar_height">

        <android.support.design.widget.CollapsingToolbarLayout
            android:id="@+id/collapsing_toolbar_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_scrollFlags="scroll|exitUntilCollapsed">

            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                style="@style/AppTheme.AppBarOverlay"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:layout_collapseMode="pin" />

        </android.support.design.widget.CollapsingToolbarLayout>

    </me.henrytao.smoothappbarlayout.SmoothAppBarLayout>

    <include layout="@layout/content_main" />

</android.support.design.widget.CoordinatorLayout>
`

**Comment by ayinmursalin** [comment]
and this is on content_main.xml

`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/content_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    tools:context="com.ayndev.a_time.MainActivity"
    tools:showIn="@layout/activity_main">

    <ListView
        android:id="@+id/listViewAlarm"
        android:layout_width="match_parent"
        android:layout_height="fill_parent">

    </ListView>

</RelativeLayout>
`

**Comment by ayinmursalin** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/content_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    tools:context="com.ayndev.a_time.MainActivity"
    tools:showIn="@layout/activity_main">

    <ListView
        android:id="@+id/listViewAlarm"
        android:layout_width="match_parent"
        android:layout_height="fill_parent">

    </ListView>

</RelativeLayout>

**Comment by henrytao-me** [comment]
Hi @ayinmursalin 

SmoothAppBarLayout doesn't work with ListView

**Comment by Jhuku** [comment]
I see that SmoothAppBarLayout works only with recycler views. Why cant it be made more generic so that it works with any view.
