### ISSUE TITLE
Toolbar inside SmoothAppBarLayout has more height than intended

### ISSUE THREAD

**Issue by oguzozcan** [henrytao-me/smooth-app-bar-layout#192]
Hello,

First of all, many thanks for the great library. I just changed my Appbar with SmoothAppBar everything is perfect except one thing. Collapsed size of the toolbar should have a size "actionBarSize" but after i switched to your library its size is bigger now.

Till now i couldn't find a way to solve this. I thought this could be about the title padding but disabling the title didn't help. Setting a AppBarLayout.Behavior to the SmoothAppBarLayout 
solves it but apperantly we dont want that.

Here you can find more details about the problem:
http://stackoverflow.com/questions/43072195/smoothappbarlayout-collapsed-toolbar-height-is-bigger-than-intended

Thanks in advance,

**Comment by henrytao-me** [comment]
Hi @oguzozcan 

Please check my answer there. Thanks. Happy coding.
