### ISSUE TITLE
Content scrolls under appbar. Scroll on NestedScrollView is doubled.

### ISSUE THREAD

**Issue by SergeyDirin** [henrytao-me/smooth-app-bar-layout#193]
I am trying to apply Smooth app bar layout and it makes my NestedScrollView go faster. It makes content of a page go under appbar when scrolling.
Can you help me with the problem?

> Edit
Sorry I found my mistake. I didn't delete app:layout_behavior parameter.

**Comment by henrytao-me** [comment]
Hi @SergeyDirin, 

Did you manage to make it work?

**Comment by SergeyDirin** [comment]
Yes thank you very much. I should have looked at your examples before
making the issue
