### ISSUE TITLE
Strange issue with toolbar title color

### ISSUE THREAD

**Issue by angryanatole** [henrytao-me/smooth-app-bar-layout#194]
Dear Henry!

First of all, thank you for your library.

I'm experiencing the following issue: for some reasons I'm unable to change the title color of the toolbar (it is always black). I know it sounds like an easy problem, but I took code from your sample project and tried to change color via attributes in style.xml (`item name="android:textColor"` in MdToolbar.Title) and with `.setTitleTextColor()` method. Also looked through the parent themes - nothing seems to override this values. Also tried to use it with different versions of support library.

Any suggestions on what may be causing the issue?

**Comment by ghost** [comment]
try setting app:popupTheme

`<style name="youAppTheme.PopupOverlay" parent="ThemeOverlay.AppCompat.Light" />`

**Comment by angryanatole** [comment]
@taatu0 thank you for your reply, unfortunatelly, I've already tried that, still no luck. Here is a screenshot taken from my emulator (same thing on my devices). The code is taken from `activity_smooth_scroll_parallax.xml`

![test](https://cloud.githubusercontent.com/assets/8074837/24770954/3da3a190-1b25-11e7-8b3b-5cdb9c31e9a2.png)

here myTheme is `<style name="MyTheme.PopupOverlay" parent="ThemeOverlay.AppCompat.Light" />`.

**Comment by angryanatole** [comment]
@taatu0 thank you for your reply, unfortunatelly, I've already tried that, still no luck. The code is taken from `activity_smooth_scroll_parallax.xml`. This is the screenshot taken on emulator (same on my devices):

![test](https://cloud.githubusercontent.com/assets/8074837/24771367/d6283e02-1b26-11e7-9a1f-734bbfcdd63e.png)

here myTheme is `<style name="MyTheme.PopupOverlay" parent="ThemeOverlay.AppCompat.Light" />`.

**Comment by taatu0** [comment]
I think you should change main text color on your appTheme with setting popupOverlay.

**Comment by ghost** [comment]
![untitle2d](https://cloud.githubusercontent.com/assets/3954034/24772308/1c69996c-1b11-11e7-864b-35d972d1b176.png)

**Comment by angryanatole** [comment]
@taatu0 oh, such a stupid mistake, I should obviously get more sleep. Thank you so much!

**Comment by henrytao-me** [comment]
Thanks @taatu0 for helping
