### ISSUE TITLE
NestedScrollView fling issue

### ISSUE THREAD

**Issue by smelfungus** [henrytao-me/smooth-app-bar-layout#197]
Hi there!
Seems like there is an open Android issue related to fling stucking with NestedScrollView on top Android versions. There are some workaronds here, I'll attach all the related links.
Is it possible for SmoothAppBarLayout to handle not the exact NestedScrollView inheritor but something that extends or implements ScrollView/NestedScrollingChild/NestedScrollingParent/ScrollingView to allow custom implementations like this one:
https://github.com/Dimezis/FlingableNestedScrollView
Related issues:
https://issuetracker.google.com/issues/37138918
http://stackoverflow.com/questions/42783030/nestedscrollview-fling-stopping-bug-on-nougat-api-25

**Comment by henrytao-me** [comment]
I will look into that issue and let you know soon.

**Comment by smelfungus** [comment]
Just tried to implement ObservableScrollingView inheritor for BaseBehavior and it is working fine as far as I can see. Will be able to make a PR after some polish if there is no free time, thank you.
