### ISSUE TITLE
Example with tabs

### ISSUE THREAD

**Issue by alirahimpour89** [henrytao-me/smooth-app-bar-layout#2]
Hi! Would love to see a example of a parallax header with a viewpager and tabs. 

Best regards, Ali.

**Comment by henrytao-me** [comment]
Cool! I am working on it. `ViewPager`, `NestScrollView` and `QuickReturn` like Google Play App Detail will be updated soon. Up to a week.

**Comment by NicodeLee** [comment]
+1

**Comment by vipinhelloindia** [comment]
+1

**Comment by henrytao-me** [comment]
I added `NestedScrollView` and `QuickReturn` examples already. Checkout `v0.1.3`

**Comment by akbarnwal** [comment]
Hello Henrytao, 
Sorry, but I am not able to see the viewPager with Tabs. 

Can you please confirm this "smooth-app-bar-layout-master" App is having  viewPager with Tabs example ?

One more thing, each tab should have RecyclerView.

Please share App link to get it if it is not.

Thanks,
Anil

**Comment by akbarnwal** [comment]
Hello Henrytao,
I tested ViewPager with tabs using current "SmoothAppBarLayout", but unfortnately it is not working properly even worse like jumping.

Please suggest by sample example like ViewPager with multiple Tabs and tab is having Recyclerview.

Thanks in Advance,
Anil

**Comment by henrytao-me** [comment]
Hi @nomad609, 
I am working on ViewPager support. The end result will be like Google Play Games / Apps section. Please stay tuned few more days! 
Also, I would like to have your opinion: how many ViewPager styles do you like to support beside these styles? 
- ViewPager + Toolbar (Google Play Games / Apps section)
- ViewPager + Parallax
- Toolbar / Parallax will be showed immediately right after scroll up (like quick return)
- Toolbar / Parallax will only be showed when scroll to top (like ExitUntilCollapsed)

**Comment by xu6148152** [comment]
very good idea

**Comment by akbarnwal** [comment]
Thanks Henrytao for fast reply and confirmation :)

I would like to work on one of the project like this link -
http://blog.grafixartist.com/wp-content/uploads/2015/09/parallax-scroll-header-tabs.png

But I tried using SmoothAppBar, but it didn't help and existing link-
http://blog.grafixartist.com/parallax-scrolling-tabs-design-support-library/

It is also not that smooth specially during scroll Up and down.

Please let us know once you complete it.

Thanks for help.

Thanks,
Anil

**Comment by henrytao-me** [comment]
PR is coming. I will deploy this weekend. Cheers!

**Comment by PedroMobile** [comment]
+1

**Comment by hardikamal** [comment]
Hi @henrytao-me can u please add listview,scrollview and recycleview in the tabs with parallaxview...Thanks

**Comment by henrytao-me** [comment]
I will deploy new version this weekend. It will support scrollView, recyclerView in tabs with parallaxView. ListView is later because I haven't tested it.

**Comment by akbarnwal** [comment]
Thanks Henry, we are waiting for good smooth version app.

**Comment by henrytao-me** [comment]
Sweeeeeeeet! version `0.1.5` is out. Check it out. ViewPager support + Inbox App and Google Play App Detail samples included.
