### ISSUE TITLE
deprecated after 26.0.0?

### ISSUE THREAD

**Issue by kassim** [henrytao-me/smooth-app-bar-layout#208]
I just switched to the support library 26.0.0 (which was causing the appbar from this library to misbehave pretty badly) and after switching out the SmoothAppBarLayout component for the official AppBarLayout, the intended "smoothness" previously provided from this library was there

I could be mistaken, but it seems like the error of the support library that this project was intended to fix, may indeed now be fixed

**Comment by henrytao-me** [comment]
Thanks for your report. I will check it later. But if it works as you mentioned, it is awesome. We are all waiting for the fix for a long long time.

**Comment by henrytao-me** [comment]
Hi @kassim, 
I confirm that the issue this library intending to fix is fixed in support library 26.0.0. Bravo support library team.

**Comment by kassim** [comment]
bravo to you, creating a working implementation that Google couldn't, at least up until now

thanks for your great work

**Comment by roman-ku** [comment]
@henrytao-me  Can you add a note to the github page? That it's deprecated _because_ the issue has been finally addressed by the support library.

Btw thanks for the great library! 👍

**Comment by roman-ku** [comment]
Also I couldn't find the fix documented here: https://developer.android.com/topic/libraries/support-library/revisions.html

**Comment by henrytao-me** [comment]
@roman-ku I added this to README already. `[DEPRECATED] Use support design 26.0.0 or above instead.` Even the fix isn't documented but it is there. I have tested it.

**Comment by roman-ku** [comment]
I wasn't sure why the library was deprecated, adding a little something about it being fixed wouldn't hurt.

**Comment by henrytao-me** [comment]
@roman-ku I updated the README to make it more clear. All the best.

**Comment by roman-ku** [comment]
Thanks!
