### ISSUE TITLE
[Know issue] Should keep ScrollView offset in ViewPager

### ISSUE THREAD

**Issue by henrytao-me** [henrytao-me/smooth-app-bar-layout#23]
Implementing ViewPager is quite tricky. 

_Step:_
- Checkout example `Smooth ViewPager`
- Scroll 1st page to x offset
- Move to 2nd page, scroll to y offset
- Back to 1st page, scroll down
- It should not move `AppBarLayout` down. 

However, thing is more complicated when you just scroll half of `AppBarLayout`. What should `AppBarLayout` move when you scroll up and down after switching tab?

**Comment by PedroMobile** [comment]
is bug on ViewPagerRunnableAdapter?

**Comment by henrytao-me** [comment]
Yes, it is. However, the root cause is from `SmoothAppBarLayout.onScrollChanged`. It's tricky to sync header (toolbar + tabLayout) offset when switching between tabs because their scroll offset are different. 
SmoothViewPager doesn't have any problem in QuickReturn mode. 
SmoothViewPager and SmoothViewPagerRunnable have the same problem because they are in ExitUntilCollapsed mode. For me, it's quite minor but it's good to have an improvement. 

If you have any idea, feel free to discuss.

**Comment by eneim** [comment]
Hi. I want to contribute to this library. But it turns out that you have your customize version of RecyclerView which cause some troubles. What is the point of that? IMO multi-layer custom dependencies is not a good practice for open source though. Please consider to put your extension of RecyclerView in this library or even consider to remove them. Using as close to the original one is best for other user to adapt your idea I suppose :D.

**Comment by henrytao-me** [comment]
Can you explain more about the issue of RecyclerView? 

I did use custom RecyclerViewAdapter, not RecyclerView. Also, the library itself doesnt depends on RecyclerViewAdapter, just the example has it as dependency.

**Comment by eneim** [comment]
Yes, but it (your custom Adapters) depends on some component of RecyclerView, for example: the LayoutManager. Furthermore, I figure out that the main problem was the proguard script which changes the LinearLayoutManager class name, therefore RecyclerView could not recognize it again. Please take care of proguard script for UI components.

About the idea of your library, the header view approach is not my style always. But i want to take a look again :D.

**Comment by henrytao-me** [comment]
Hi @eneim 
I sent another PR for fixing proguard internally. You don't have to specify this library in your proguard file anymore. 

If some how Support Design version xxx can fix the laggy issue with non-header approach, we can move back to origin. For now, most of Google Apps (Inbox, Google Play, Google Contact...) are using header approach (I believe). 

If you have any idea or found something are interesting, don't hesitate to share here. Thanks a lot!

**Comment by Deepankur-Sadana** [comment]
Hi @henrytao-me, I have an idea to solve this bug. When you scroll back to the 1st viewpager which has x offset, the AppbarLayout should come down only at the top of the recycler view (essentially after scrolling back to the 1st entry). Any recommendations of how we could achieve that?

**Comment by henrytao-me** [comment]
Hi @Deepankur-Sadana, the tricky part is calculating totalScrollOffset of RecyclerView which I still don't know what is the best solution.

**Comment by Deepankur-Sadana** [comment]
Hi @henrytao-me  , no problems I am on it. I will have you know the solution if I am able to deal with it .
I appreciate you for acknowledging the concern.

**Comment by henrytao-me** [comment]
Thanks a lot. Let me know if you find something interesting.

**Comment by henrytao-me** [comment]
Hi @PedroMobile @eneim @Deepankur-Sadana 

Check out `v1.0.2`. ViewPager now supports `exitUntilCollapsed` and `quickReturn` too. They are all interesting.
