### ISSUE TITLE
scrollToPosition(0) not working

### ISSUE THREAD

**Issue by ssung99** [henrytao-me/smooth-app-bar-layout#24]
RecyclerView scrolls (intermediate list) AppBarLayout this state when collased
Calling the scrollToPosition (0)
AppBarLayout is not expanded
If forced to call a appBarLayout.setExpanded () it seems one normally seen
When you scroll through the list it disappears immediately.

**Comment by henrytao-me** [comment]
Hi @ssung99 
Can you give more information about your issue? 
- What example are you using? 
- Can you post your layout? 
- Do you use ViewPager? 
- If you are using ViewPager, can you post your adapter?

**Comment by ssung99** [comment]
Hi @henrytao-me 

use SmoothSwipeRefreshLayout, not ViewPager

SmoothAppBarLayout sample app excute ->
SmoothSwipeRefreshLayout select ->
list up scroll -> 
focus "Line 10", AppBarLayout state is collapsed  ->
Forced to call scrollToPosition(0) 

I want,,
list focus "Line 0", AppBarLayout  state is expanded

but
list header show (blank paddingTop area)

**Comment by henrytao-me** [comment]
Have you tried `recyclerView.smoothScrollToPosition(0)` instead of `recyclerView. scrollToPosition(0)`?

**Comment by ssung99** [comment]
I already also calls smoothScrollToPosition(0)
Well not,

Forced call appBarLayout.setExpanded()

But his good showing It disappears when you scroll right

**Comment by henrytao-me** [comment]
Let me check tonight

**Comment by ssung99** [comment]
Thank you so much~

I saw test

When the number of the list changes, item is added to the list
Calling recyclerView.smoothScrollToPosition(0), AppBarLayout does not seem to expand

**Comment by henrytao-me** [comment]
Hi @ssung99 

I still can not imagine your scenario. Can you record a video? However, `SmoothAppBarLayout` has method call `syncOffset()` and `syncOffsetDelayed(int delayMillis)` which can help in some cases. Ex: remove items from RecyclerView, manually changing scroll offset. 

Can you try this?

```
recyclerView. scrollToPosition(0);
smoothAppBarLayout.syncOffset();
// or 
// smoothAppBarLayout.syncOffsetDelayed();
// smoothAppBarLayout.syncOffsetDelayed(500);
```

**Comment by henrytao-me** [comment]
Hi @ssung99 

There are 2 ways to solve your scenarios. I added some examples here. 
Checkout this branch https://github.com/henrytao-me/smooth-app-bar-layout/tree/issue-24 

You can also checkout this diff https://github.com/henrytao-me/smooth-app-bar-layout/commit/7dab3c0678fd04818f2fc707b751b10adcc780f7

Let me know if this issue is fixed. By default, I will close this ticket tomorrow. 

Happy coding!

**Comment by ssung99** [comment]
Unfortunately, 
mp4 file is unsupported file type.  

![Uploading 20151013113352.jpg…]()

**Comment by ssung99** [comment]
Unfortunately, 
mp4 is unsupported file type.  

![Uploading 20151013113352.jpg…]()

list scrolling (list focus is located in the middle of the list) -> 
add item (As it is shown in the image flie "# Line 0") ->
call smoothScrollToPosition(0)

**Comment by henrytao-me** [comment]
What's happened @ssung99 ?

**Comment by henrytao-me** [comment]
Can you upload to youtube?

**Comment by ssung99** [comment]
![20151013113352](https://cloud.githubusercontent.com/assets/15084536/10444359/7e03ce48-71a0-11e5-9757-726c2ce69c10.jpg)

list scrolling (list focus is located in the middle of the list) -> 
add item (As it is shown in the image flie "# Line 0") ->
call smoothScrollToPosition(0)

**Comment by henrytao-me** [comment]
What's the step to reproduce that issue? Did you try my suggestion? https://github.com/henrytao-me/smooth-app-bar-layout/commit/7dab3c0678fd04818f2fc707b751b10adcc780f7

**Comment by ssung99** [comment]
The latest source is right !

getSampleData() modified

  protected List<String> getSampleData() {
      List<String> data = new ArrayList<>();

```
  int i = 0;
  for (int n = ITEM_COUNT; i < n; i++) {
               data.add(String.format("Line %d", i));
  }

  for (i = 0; i < count; i++) {
      data.add(i, String.format("# Line %d", i));
  }
  count++;

  return data;
```

  }

private void initAdapter() {
        adapter = new SimpleRecyclerViewAdapter(new SimpleAdapter<>(getSampleData(), null)
               {
            @Override
            public RecyclerView.ViewHolder onCreateFooterViewHolder(LayoutInflater layoutInflater, ViewGroup viewGroup) {
                return null;
            }

```
        @Override
        public RecyclerView.ViewHolder onCreateHeaderViewHolder(LayoutInflater layoutInflater, ViewGroup viewGroup) {
            return new HeaderHolder(layoutInflater, viewGroup, R.layout.item_header_spacing);
        }
    };

    vRecyclerView.setAdapter(adapter);
}

@Override
public void onRefresh() {

    new Handler().postDelayed(new Runnable() {
        @Override
        public void run() {
            if (isAdded() && vSwipeRefreshLayout != null) {
                vSwipeRefreshLayout.setRefreshing(false);

                initAdapter();

                vRecyclerView.smoothScrollToPosition(0);
            }
        }
    }, 2000);
}
```

step is

SwipeRefreshLayout pull -> 
list scrolling (list focus is located in the middle of the list)

**Comment by ssung99** [comment]
As you have told us advice

methd  call syncOffsetDelayed()

---->
recyclerView.scrollToPosition(0);
appBarLayout.syncOffsetDelayed();

i'm happy to slove~~
It is so much thanks

**Comment by henrytao-me** [comment]
I see the problem. While you call `initAdapter();`, the RecyclerView doesn't have any scroll offset. It's can not do any smoothscroll either. That's why you need to delay it. 

I think problem is solved.

**Comment by hrsalehi** [comment]
I have the same issue. when I call `setExapnded(false,true)` (for scrolling app bar programmatically with animation) for `SmoothAppBarLayout` the nested scroll view doesn't scrolled and remain still.
