### ISSUE TITLE
Improve text scaling

### ISSUE THREAD

**Issue by sdex** [henrytao-me/smooth-app-bar-layout#26]
Hello. 

I think, it will be nice to use text scaling like in default implementation of [CollapsingToolbarLayout](https://android.googlesource.com/platform/frameworks/support/+/6ba61c5/design/src/android/support/design/widget/CollapsingToolbarLayout.java#234) instead of setTextSize in [SmoothCollapsingToolbarLayout](https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/smooth-app-bar-layout/src/main/java/me/henrytao/smoothappbarlayout/SmoothCollapsingToolbarLayout.java#L303). Current implementation leads to text jerks.
There is a [helper class (CollapsingTextHelper)](https://android.googlesource.com/platform/frameworks/support/+/6ba61c5/design/src/android/support/design/widget/CollapsingTextHelper.java) that handle it in the design library.

Thanks for useful library.

**Comment by henrytao-me** [comment]
Hi @sdex 
Thanks for your suggestion. Let me include that in the next release. :ok_hand:

**Comment by henrytao-me** [comment]
Hmmmmmmm. Look like it's quite tricky to translate and scale all `title`, `subtitle` and `avatar` correctly.

**Comment by petersnoopy** [comment]
+1
