### ISSUE TITLE
SmoothNestedScrollViewParallax2Fragment does not work with new v7:23.1.0 library

### ISSUE THREAD

**Issue by 3mph4515** [henrytao-me/smooth-app-bar-layout#27]
Google updated their support-design library to v7:23.1.0 and it seems like smooth nested scrollview doesn't work correctly now.

Header can moves separately from the main view. Watch this video 
http://tinypic.com/player.php?v=2q24cwn%3E&s=8#.VikCNvkrKUk

Reverting to v7:23.0.1 fix the issue.

**Comment by henrytao-me** [comment]
I see. I will fix it soon. Thanks a lot.

**Comment by henrytao-me** [comment]
Hi @3mph4515 

Can you provide more information about that issue? I tested with support `23.1.0`, it works normally.
- Which version of `smooth-app-bar-layout` are you using?
- Are you playing with the example apk on Google Play or your own project? 
- What device are you using? What android version is it?

**Comment by henrytao-me** [comment]
Wait. I see what you mean. Here is from Support Design `23.1.0`: `You’ll also find that AppBarLayout now allows users to start scrolling from within the AppBarLayout rather than only from within your scrollable view - this behavior can be controlled by adding a DragCallback.` Let me investigate.

**Comment by henrytao-me** [comment]
Hey,

Checkout version `0.2.0`. It is fixed. It's interesting to have `DragCallback` in support design `23.1.0`. However, it's still buggy. I disabled it by default.

**Comment by 3mph4515** [comment]
It was smooth-app-bar from last 0.1.9 library. And I just edit your own sample project from git. 

Now it works like a charm. Thank you.

P.S. They said fling issue was fixed in 23.1.0. Nice try, Android team :+1:

**Comment by henrytao-me** [comment]
Sweeeeeet. Enjoy!
