### ISSUE TITLE
why can not use minifyEnabled true???

### ISSUE THREAD

**Issue by ximida** [henrytao-me/smooth-app-bar-layout#29]
why can not use minifyEnabled true???

**Comment by henrytao-me** [comment]
Yo @ximida 

I put some note in README. Please try this: `Please make sure all classes aren't shrinked or minified by proguard.`

```
-keep class me.henrytao.smoothappbarlayout.** { *; }
```

Let me know if it works. I will close this ticket. ;)

**Comment by ximida** [comment]
sorry, I wrote it wrongly, I use shrinkResources true, than I can not generate signed release APK .Why??

**Comment by henrytao-me** [comment]
Hi,

If you are using other libraries, please check out their progruard configurations too. Ex: `butterKnife`... Check out my sample app here. It works!

https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/sample/build.gradle#L16
https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/sample/proguard-rules.pro#L19

**Comment by henrytao-me** [comment]
I think I should close it. Let me know if you have that problem again.
