### ISSUE TITLE
Can it solve the wrong Scrolling ....?

### ISSUE THREAD

**Issue by asker517** [henrytao-me/smooth-app-bar-layout#3]
hard to decscribe.. just like this
[Video](https://www.youtube.com/watch?v=uVMvLVGQlOk)
when you do short and quick fling ...

**Comment by henrytao-me** [comment]
Right. It's exactly what this library is solving. Checkout some examples on the right side in the demo app. I will  add quick return animation and more examples like `ViewPager` and `NestedScrollView` soon. Up to a week.

**Comment by asker517** [comment]
amazing ， looking forward :D
2015年9月29日 21:44，"Henry Tao" notifications@github.com写道：

**Comment by henrytao-me** [comment]
I updated NestedScrollView examples and some improvements. Check it out v0.1.2
