### ISSUE TITLE
Remove items

### ISSUE THREAD

**Issue by AlexNsbmr** [henrytao-me/smooth-app-bar-layout#30]
When the header is collapsed and we remove items in the `RecyclerView` and we scroll back to the top, the header still appears collapsed with the empty space created by the item. We need to scroll twice to make the header appear again.

Would it be possible to achieve to make the header follow the new height of the `RecyclerView` after a item removal ? 

I'm using a RecyclerView with `android:clipToPadding="false"` and `android:paddingTop="@dimen/image_height"`

@henrytao-me Thanks so much for this amazing and useful library!

**Comment by henrytao-me** [comment]
Hi @AlexNsbmr 

`SmoothAppBarLayout` has a method called `syncOffset` and `syncOffsetDelayed`. After removing some items in recyclerView, you can call one of these methods to refresh appbar offset.  [Check out this link - SmoothAppBarLayout - L151](https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/smooth-app-bar-layout%2Fsrc%2Fmain%2Fjava%2Fme%2Fhenrytao%2Fsmoothappbarlayout%2FSmoothAppBarLayout.java#L151)

You don't need to care about syncing offset when new items are added. 

Sorry, I haven't put it into the wiki yet. Let me know if it solves the problem. Cheers!

**Comment by AlexNsbmr** [comment]
@henrytao-me That worked like a charm, thanks a lot for the help and keep up the good work!

**Comment by henrytao-me** [comment]
Thank man. Nice to know you are using this library. ;) Please help to spread it out ;)
