### ISSUE TITLE
Should remove app_name string and <application> tag in AndroidManifest.xml

### ISSUE THREAD

**Issue by h6ah4i** [henrytao-me/smooth-app-bar-layout#33]
Hi. I noticed some small issues.

First, the `app_name` string resource should be removed from the library module in order to avoid same resource name conflictions.

Second, `<application>` tag in `AndroidManifest.xml` of the library module should be removed also. It will conflict with user application and we need to specify `tools:replace="android:label"` in user app's `AndroidManifest.xml`.

Thanks.

**Comment by henrytao-me** [comment]
Sweet. Love to fix this issue.
