### ISSUE TITLE
Programmatically child scroll

### ISSUE THREAD

**Issue by devindi** [henrytao-me/smooth-app-bar-layout#36]
Hi, I used that lib and all is ok.

my xml

``` java
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:fab="http://schemas.android.com/apk/res-auto"
xmlns:app="http://schemas.android.com/tools"
android:layout_width="match_parent"
android:layout_height="match_parent"
android:background="#eaeaea"
android:id="@+id/root">

    <android.support.v4.view.ViewPager
        android:id="@+id/viewpager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:visibility="gone"
        android:background="#eaeaea"/>

       <me.henrytao.smoothappbarlayout.SmoothAppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/app_bar_layout">

        <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
            android:layout_width="match_parent"
            android:layout_height="240dp">
             <!-- my stuff-->
        </FrameLayout>

        <include layout="@layout/view_tab_layout"/>

    </me.henrytao.smoothappbarlayout.SmoothAppBarLayout>

</android.support.design.widget.CoordinatorLayout>

```

I have NesedScrollView at Viewpager and I do scrollView.scrollTo(0, 5000) scroll view scrolled but app bar layout didn't. 

What I am doing wrong?

**Comment by henrytao-me** [comment]
Hi @devindi 

There are 2 ways to do that. 
- First, you can call `SmoothAppBarLayout.syncOffset` or `SmoothAppBarLayout.syncOffsetDelayed` after calling `scrollView.scrollTo(0, 5000)`. Check out here [syncOffset](https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/smooth-app-bar-layout%2Fsrc%2Fmain%2Fjava%2Fme%2Fhenrytao%2Fsmoothappbarlayout%2FSmoothAppBarLayout.java#L151)
- Second, you can call `scrollView.smoothScrollTo(0, 5000)`. 

I hope it helps. 

Cheers, 
Henry

**Comment by devindi** [comment]
Hi @henrytao-me 
Thanks for your advices but it didn't help me =( I still see app bar

**Comment by henrytao-me** [comment]
Weird. Do you want to have Skype call or Teamviewer?
