### ISSUE TITLE
Flinging creates a blank space

### ISSUE THREAD

**Issue by Mariovc** [henrytao-me/smooth-app-bar-layout#4]
If you hide the appbar a bit (scrolling up half way) and then fling fast down, the recycler view scrolls good but the app bar stays on the same place.

**Comment by henrytao-me** [comment]
Can I know which example did you mention and what device are you using?

**Comment by Mariovc** [comment]
It is happening in all the examples of your demo app. Here is only one:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/3913433/10179515/c0332f7e-6706-11e5-99c3-2b86660f6161.gif)

**Comment by asker517** [comment]
yes，it exist all kinds of smoothappbar demo
2015年9月30日 06:04，"Mariovc" notifications@github.com写道：

**Comment by Mariovc** [comment]
I have used a OnePlus One with Android 5.1.1 and this demo app version 0.1.0
https://play.google.com/store/apps/details?id=me.henrytao.smoothappbarlayout

**Comment by henrytao-me** [comment]
It's fixed. Check out version 0.1.1. Thanks!

**Comment by henrytao-me** [comment]
It's improved but still there in some cases. Let me look into it.

**Comment by henrytao-me** [comment]
It's fixed in v0.1.2. Check it out https://play.google.com/store/apps/details?id=me.henrytao.smoothappbarlayout
