### ISSUE TITLE
resetOffset when appBarLayout expanded

### ISSUE THREAD

**Issue by zoopolitic** [henrytao-me/smooth-app-bar-layout#40]
In new version of design library was added setExpanded() method which expands AppBar, however scroll and translation are not reset on this event. Need to add event to reset mCurrentScrollOffset, mCurrentTranslationOffset when AppBarLayout expands, otherwise there is wrong behaviour

**Comment by henrytao-me** [comment]
Let me look into it.

**Comment by henrytao-me** [comment]
Can you upload a video to demonstrate the issue? @zoopolitic. `SmoothAppBarLayout` has few methods that you can use to sync `offset`, especially when you add new item to RecyclerView, ListView or ScrollView. Check out here [syncOffset](https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/smooth-app-bar-layout%2Fsrc%2Fmain%2Fjava%2Fme%2Fhenrytao%2Fsmoothappbarlayout%2FSmoothAppBarLayout.java#L151) and [syncOffsetDelayed](https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/smooth-app-bar-layout%2Fsrc%2Fmain%2Fjava%2Fme%2Fhenrytao%2Fsmoothappbarlayout%2FSmoothAppBarLayout.java#L162). 

Is that what you are looking for?
