### ISSUE TITLE
MDToolbar Theme

### ISSUE THREAD

**Issue by myscreen** [henrytao-me/smooth-app-bar-layout#41]
Hi, Thanks for your awesome library. According to your 3 steps, I just add your library from gradle compile "me.henrytao:smooth-app-bar-layout:0.2.1" and change the Remove app:layout_behavior="@string/appbar_scrolling_view_behavior".
Add header to your scroll view or recyclerView. Or set paddingTop and clipToPadding="false".

When I wanna build, it is looking for AppStyle.MdToolbar. I would appreciate if you don't mind helping me to resolve this issue.

Thanks and Best Regards

**Comment by henrytao-me** [comment]
Hi @myscreen, 

There are 2 ways you can fix it.
- You can ignore `AppStyle.MdToolbar` and create your Toolbar style. 
- You can add bootstrap library `android-md-core` [here](https://github.com/henrytao-me/android-md-core). However, I don't recommend this way for now because it's under development. I am still working on v2 release for `android-md-core`.

Thanks for using this library. Love to help you!

**Comment by myscreen** [comment]
Thanks for replay. The issue is that by removing mdtollbar it cant work. So code below is what I attempt to run but the parallax does not move.

<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

```
<android.support.v4.view.ViewPager
    android:id="@+id/view_pager"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />

<me.henrytao.smoothappbarlayout.SmoothAppBarLayout
    android:layout_width="match_parent"
    android:layout_height="256dp">

    <android.support.design.widget.CollapsingToolbarLayout
        android:id="@+id/collapsing_toolbar_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:contentScrim="?attr/colorPrimary"
        app:layout_scrollFlags="scroll|exitUntilCollapsed">

        <ImageView
            android:id="@+id/cover"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@drawable/preimage"
            android:scaleType="centerCrop"
            app:layout_collapseMode="parallax" />

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_height="104dp"
            android:background="@android:color/black"
            android:gravity="top"
            android:minHeight="?attr/actionBarSize"
            app:layout_collapseMode="pin"
            app:navigationIcon="@drawable/ic_app_notification_logo"
            app:titleMarginTop="13dp"
             />

        <android.support.design.widget.TabLayout
            android:id="@+id/tab_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom" />
    </android.support.design.widget.CollapsingToolbarLayout>
</me.henrytao.smoothappbarlayout.SmoothAppBarLayout>
```

</android.support.design.widget.CoordinatorLayout>

**Comment by henrytao-me** [comment]
Please change `Toolbar` to this

```
<android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_height="?attr/actionBarSize"
            android:background="@android:color/black"
            android:gravity="top"
            android:minHeight="?attr/actionBarSize"
            app:layout_collapseMode="pin"
            app:navigationIcon="@drawable/ic_app_notification_logo"
            app:titleMarginTop="13dp"
             />
```

If you set `layout_height` bigger than `actionBarSize`, it won't work. It also happens on original AppBarLayout implementation.

**Comment by myscreen** [comment]
Thanks again for your replay.
without style app work however the parallax not moving up. it cant move. when I add style it gets below error.

java.lang.RuntimeException: Failed to resolve attribute at index 3
            at android.content.res.TypedArray.twGetColorStateList(TypedArray.java:438)
            at android.content.res.TypedArray.getColorStateList(TypedArray.java:420)
            at android.widget.TextView.setTextAppearance(TextView.java:3029)
            at android.support.v7.widget.Toolbar.setTitle(Toolbar.java:611)
            at android.support.v7.internal.widget.ToolbarWidgetWrapper.setTitleInt(ToolbarWidgetWrapper.java:286)
            at android.support.v7.internal.widget.ToolbarWidgetWrapper.setWindowTitle(ToolbarWidgetWrapper.java:268)
            at android.support.v7.internal.app.ToolbarActionBar.<init>(ToolbarActionBar.java:82)
            at android.support.v7.app.AppCompatDelegateImplV7.setSupportActionBar(AppCompatDelegateImplV7.java:206)
            at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:99)
            at example.com.finalmyscreenapp.TabParallax.TabsHeaderActivity.onCreate(TabsHeaderActivity.java:75)
            at android.app.Activity.performCreate(Activity.java:6500)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3218)
            at android.app.ActivityThread.access$1000(ActivityThread.java:198)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6837)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

I added the     compile'me.henrytao:mdcore:1.9.11'

and in style I added     

<style name="AppStyle.MdToolbar" parent="MdToolbar">
        <item name="android:elevation" tools:targetApi="lollipop">0dp</item>
</style>

Thanks

**Comment by henrytao-me** [comment]
I would say you don't need to use `mdcore`. I will create another demo for you when I am back home. It'll roughly take few hours. I will ping you soon.

**Comment by myscreen** [comment]
Thanks, I am waiting for you. Thanks again

**Comment by henrytao-me** [comment]
Hi @myscreen, 

Check out my `fresh` module here https://github.com/henrytao-me/smooth-app-bar-layout/tree/issue-41

Good luck.

**Comment by myscreen** [comment]
Thanks so much. now I am working on it. I will inform you asap. But I have other question. I am using https://github.com/Yalantis/Phoenix as pull to refresh. Can you explain to me how we can use it with yours together. if you dont mind. thanks

**Comment by myscreen** [comment]
![screenshot_2015-12-01-00-02-49](https://cloud.githubusercontent.com/assets/14212198/11476686/0587ccf4-97bf-11e5-88f0-b6f1aa229525.png)
I added same as your fresh project. But one difference is that I havent use fragment with ObservableScrollView. I use simple fragment with Recyclerview. The Parallax not moving but list scrolling under parallex. 

<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context="example.com.finalmyscreenapp.TabParallax.TabsHeaderActivity">

```
<android.support.v4.view.ViewPager
    android:id="@+id/view_pager"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />

<me.henrytao.smoothappbarlayout.SmoothAppBarLayout
    android:layout_width="match_parent"
    android:layout_height="256dp">

    <android.support.design.widget.CollapsingToolbarLayout
        android:id="@+id/collapsing_toolbar_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:contentScrim="?attr/colorPrimary"
        app:layout_scrollFlags="scroll|exitUntilCollapsed">

        <ImageView
            android:id="@+id/cover"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@android:color/holo_red_dark"
            android:scaleType="centerCrop"
            app:layout_collapseMode="parallax" />

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="104dp"
            android:background="@android:color/transparent"
            android:gravity="top"
            android:minHeight="?attr/actionBarSize"
            app:layout_collapseMode="pin"
            app:titleMarginTop="13dp" />

        <android.support.design.widget.TabLayout
            android:id="@+id/tab_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom" />
    </android.support.design.widget.CollapsingToolbarLayout>
</me.henrytao.smoothappbarlayout.SmoothAppBarLayout>
```

</android.support.design.widget.CoordinatorLayout>

I am so sorry to disturb you.

**Comment by henrytao-me** [comment]
Hi @myscreen 

Check out develop branch. I added 2 examples for customizing PullToRefresh. It should work normally with current release. 

What is your issue then? Can you make a video?

**Comment by myscreen** [comment]
Hi, since morning I am reviewing your code. thanks so much for fast response. Not yet being successful but I do my best. Because I would like to have viewpager with recyclerview list + phonix pull to refresh. For having this, does it require special layout or just merging booth your sample is enough. Thanks and I update you asap.

**Comment by myscreen** [comment]
![screenshot_2015-12-01-18-55-39](https://cloud.githubusercontent.com/assets/14212198/11498921/606a7560-985d-11e5-8ab0-022f8eb855e4.png)

Hi, after many hours with your best supports, I have reach to run without error viewpager type but without rcyclerview. Now I added the recyclerview which I used https://github.com/yasevich/endless-recycler-view .
The picture that I attached shows that when I scroll down many pages, at return to top of the page, the parallax cant be move to its position. Please advice me how can I use it.
My layout for fragment is:

<com.yalantis.phoenix.PullToRefreshView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/pull_to_refresh"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

```
<com.github.yasevich.endlessrecyclerview.EndlessRecyclerView
    android:id="@+id/listVideos"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />
```

</com.yalantis.phoenix.PullToRefreshView>

and the main layout is:

<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

```
<android.support.v4.view.ViewPager
    android:id="@+id/view_pager"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />

<me.henrytao.smoothappbarlayout.SmoothAppBarLayout
    android:id="@+id/smooth_app_bar_layout"
    android:layout_width="match_parent"
    android:layout_height="256dp">

    <android.support.design.widget.CollapsingToolbarLayout
        android:id="@+id/collapsing_toolbar_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:contentScrim="?attr/colorPrimary"
        app:layout_scrollFlags="scroll|exitUntilCollapsed">

        <ImageView
            android:id="@+id/cover"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@drawable/preimage"
            android:scaleType="centerCrop"
            app:layout_collapseMode="parallax" />

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_height="50dp"
            android:layout_width="fill_parent"
            android:background="@android:color/transparent"
            android:gravity="top"
            android:minHeight="?attr/actionBarSize"
            app:layout_collapseMode="pin"
            app:titleMarginTop="13dp"
             />
        <!--style="@style/AppStyle.MdToolbar"-->
        <!--app:navigationIcon="@drawable/bs_ic_more"-->

        <android.support.design.widget.TabLayout
            android:id="@+id/tab_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom" />
    </android.support.design.widget.CollapsingToolbarLayout>
</me.henrytao.smoothappbarlayout.SmoothAppBarLayout>
```

</android.support.design.widget.CoordinatorLayout>

at the end, according to your sample, you have not implement the ObservableScrollView for recyclerview list but in my case it could not move without it.

Thanks and Best Regards

**Comment by henrytao-me** [comment]
Hi @myscreen 

When the content of ScrollView / ListView / RecyclerView is added dynamically, it's tricky to notify automatically. So that, you have to call [syncOffset](https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/smooth-app-bar-layout%2Fsrc%2Fmain%2Fjava%2Fme%2Fhenrytao%2Fsmoothappbarlayout%2FSmoothAppBarLayout.java#L151) or [syncOffsetDelayed](https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/smooth-app-bar-layout%2Fsrc%2Fmain%2Fjava%2Fme%2Fhenrytao%2Fsmoothappbarlayout%2FSmoothAppBarLayout.java#L171) in `SmoothAppBarLayout` right after the content is changed (both added and removed). 

Let me know if it solves your issue.

**Comment by myscreen** [comment]
hi, It is working but from other fragment calling SmoothAppBarLayout , syncOffset  is not a good way because sometimes it refers to null object. I have one fragment for my list and viewpager is at other fragment. so calling those function is difficult.
however still it working and thanks so much for your great warms supports. I have attempted to buy a coffee for you from your sample app however unfortunately Google says it is not compatible in your app. Please inform me how I can buy some coffee for you ;) I am waiting.

**Comment by henrytao-me** [comment]
Thank for your support. I just test with my friend. The donation works on my side. :o. Hmmmmmm.

**Comment by myscreen** [comment]
hi give me alternative to buy coffee pls ;(

**Comment by henrytao-me** [comment]
Hi @myscreen 

Thanks. You can buy me a coffee here. I just add that. https://github.com/henrytao-me/smooth-app-bar-layout#donation
