### ISSUE TITLE
Programatically scrolling to bottom of RecyclerView causes problems

### ISSUE THREAD

**Issue by matejhacin** [henrytao-me/smooth-app-bar-layout#42]
I always scroll to the bottom of RecyclerView as soon as it has data like this:

vRecyclerView.scrollToPosition(adapter.getItemCount() - 1);

I am trying to use Smooth Parallax and this causes problems. Toolbar doesn't collapse when it is scrolled to the bottom, so you have to scroll up and then back down for it to disappear.

What I want is simple. When activity starts, RecyclerView is scrolled to the bottom and Toolbar collapses, so that ImageView is not visible, only normal Toolbar is. Then when user scrolls to the top, parallax happens.

Is this possible?

I know this library is solving a different problem, but if this was possible, it would be awesome!

**Comment by henrytao-me** [comment]
Hi @matejhacin 
Check out [syncOffset](https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/smooth-app-bar-layout%2Fsrc%2Fmain%2Fjava%2Fme%2Fhenrytao%2Fsmoothappbarlayout%2FSmoothAppBarLayout.java#L151) and [syncOffsetDelayed](https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/smooth-app-bar-layout%2Fsrc%2Fmain%2Fjava%2Fme%2Fhenrytao%2Fsmoothappbarlayout%2FSmoothAppBarLayout.java#L171) in `SmoothAppBarLayout` after calling `scrollToPosition`. 

Let me know if it solves your issue.

**Comment by matejhacin** [comment]
Thanks for the reply, I just tried both of those methods but it sadly doesn't work. Nothing happens differently at all.

Any other ideas maybe?

**Comment by henrytao-me** [comment]
Can you extract your project to somewhere that I can review?

**Comment by matejhacin** [comment]
I was actually simply testing it out by editing your sample code. I edited the "Smooth parallax" sample.

I only added two lines:

```
vRecyclerView.scrollToPosition(adapter.getItemCount() - 1);
appBar.syncOffset();
```

**Comment by henrytao-me** [comment]
Thank @matejhacin. Let me try when I am back home.

**Comment by henrytao-me** [comment]
Hi @matejhacin,

Check out branch [issue-42](https://github.com/henrytao-me/smooth-app-bar-layout/tree/issue-42) and version `0.2.2`. I fixed it.

**Comment by matejhacin** [comment]
That is awesome! Thanks!
