### ISSUE TITLE
*videos included* Weird scroll offset when using any custom recycler view 

### ISSUE THREAD

**Issue by osiloke** [henrytao-me/smooth-app-bar-layout#43]
Hi, i'm using this library with [android-advancedrecycleview's](https://github.com/h6ah4i/android-advancedrecyclerview) expandable list function. I get two different behaviours when i use with your library and android appbar layout. The videos below explain it.

Using your library 
Video: https://vid.me/ArFg
Xml: https://gist.github.com/osiloke/03ba1f060ec8434a3786
Using support library 
Video: https://vid.me/IptD
Xml: https://gist.github.com/osiloke/d125d57a653a434f13d1

As you can see from the second video. The full grouped list shows. 
Any help, is great help

**Comment by henrytao-me** [comment]
Hi @osiloke 
`SmoothAppBarLayout` and `AppBarLayout` are using different approach. With `SmoothAppBarLayout` you have to specify header spacing for RecyclerView. Try to get the height of your `Carpaccio` view, then add paddingTop to RecyclerView like this: 

``` xml
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <android.support.v7.widget.RecyclerView
        android:id="@android:id/list"
        android:paddingTop="@dimen/your_carpaccio_height"
        android:clipToPadding="false"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"
        style="@style/myRecyclerViewStyle"/>
...
```

**Comment by osiloke** [comment]
cool, thanks
