### ISSUE TITLE
Better fix for this issue

### ISSUE THREAD

**Issue by remcomokveld** [henrytao-me/smooth-app-bar-layout#48]
This is not really an issue, but i just wanted to let you know that i have been searching through recyclerview and nestedscrollview and i have found the real bug in those views. Check out this issue https://code.google.com/p/android/issues/detail?id=195800. In comment #3 is a replacement of nestedscrollview and a subclass of recyclerview which correctly dispatch any rest velocity to the nestedscrollingparent aka Coordinatorlayout which then applies the fling to the appbar as well. Please all star this issue because i posted it two weeks ago and it still has not even been assigned

**Comment by henrytao-me** [comment]
You got my credit. I starred it. Looking forward to see response from android team.
