### ISSUE TITLE
Spacing Header Issue

### ISSUE THREAD

**Issue by myscreen** [henrytao-me/smooth-app-bar-layout#49]
Hi, I would like to know is there any posibility to use spacing header out of adapter because I have adapter which has already sticky headers and I cant add extra spacing header. Even I add in XML Layout it is not working. Thanks man ;)

**Comment by henrytao-me** [comment]
Hi @myscreen 
You can use this wrapper adapter https://github.com/henrytao-me/recyclerview-multistate-section-endless-adapter. The idea is: your sticky header and list item will be `BaseAdapter`. The header spacing will be included in `WrapperAdapter`. `WrapperAdapter` will be passed into `RecyclerView`.

Check it out and let me know if it helps.
