### ISSUE TITLE
Add new feature for Toolbar

### ISSUE THREAD

**Issue by Fshamri** [henrytao-me/smooth-app-bar-layout#52]
I have my toolbar/appbar layout is in activity and in fragment i have either recyclerView or LinearLayout where the first view  is imageView header of certain height say 200dp. here i want to have toolbar to be transparent and change its background alpha to primary color when scroll down and back to transparent background when scroll up  

It will be greate if you add new this feature.

Thnaks

**Comment by henrytao-me** [comment]
Hi @Fshamri,

Did you check my example app? Check out `Google Play` and `SmoothViewPagerParallaxDrawerLayout` demo.

**Comment by Fshamri** [comment]
got it..  thanks a lot
