### ISSUE TITLE
AppBar scroll problem on (animated) layout height change of row height

### ISSUE THREAD

**Issue by arberg** [henrytao-me/smooth-app-bar-layout#55]
Hi, 

The Smooth app bar has a scroll problem when the row height of the recyclerview items are animated. The problems appears for the Enter Always scroll-mode, where the appbar exits completely and only enters when recyclerview is scrolled to the top.

I have created a branch with sample code which illustrates the problem (more on this below): https://github.com/arberg/smooth-app-bar-layout/tree/debug_appbar_scroll_on_layout_change

I can reproduce the problem like this:
- Expand the height of the top row in onClickListener by animating from normal small size to eg. 2x screen size. I set update layoutHeight and run requestLayout on each frame.
- After expansion I scroll down to bottom part of top row, so appbar scrolls completely out of view. 
- Shrink the top row again
- Scoll up to top:
  Problem: Now appbar does not appear immediately but I have to scroll further, to make appbar appear.

The problem can also be reproduced in another way, which perhaps illustrates the root cause. Instead of animating the rows I just expand immediately onBind. If the expanded state is cached in adapter, then the appbar behaves correctly. If the expanded state is not cached in adapter, so that when an expanded view is reused it will still be expanded, then it causes problems. 
- Expand top row, in onclicklistener
- Scroll down until the top viewholder is reused and an expanded row comes into view
- click expanded row to shrink it
- scroll up to top again
  Problem: Again appbar does not appear immediatly after reating top row.

Sample code is here
https://github.com/arberg/smooth-app-bar-layout/tree/debug_appbar_scroll_on_layout_change

In SimpleAdapter set 
ENABLE_ANIMATION = true;
ENABLE_CACHED_STATE = true;
to get 1. mentioned animated behavior.

Set both to false, to get the second mentioned behavior.

PS: I changed build.gradle a bit for minSdk for animation and debugVariant so I could debug.
PPS: Click 'Enter Always' to and follow guide above to reproduce problems. For |enterAlwaysCollapsed quick return, then the problem is visible also then reaching top row.

Best Alex

**Comment by henrytao-me** [comment]
Hi @arberg,

Thanks for your report. I am really appreciate. Let me check.

**Comment by henrytao-me** [comment]
Can you add me as a collaborator in your fork repo? I would like to send some PRs

**Comment by henrytao-me** [comment]
In general, the solution is: if items in RecyclerView are changed height or removed, we have to explicitly call [syncOffset](https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/smooth-app-bar-layout%2Fsrc%2Fmain%2Fjava%2Fme%2Fhenrytao%2Fsmoothappbarlayout%2FSmoothAppBarLayout.java#L151) or [syncOffsetDelay](https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/smooth-app-bar-layout%2Fsrc%2Fmain%2Fjava%2Fme%2Fhenrytao%2Fsmoothappbarlayout%2FSmoothAppBarLayout.java#L162) depending on situation.

**Comment by arberg** [comment]
I have added you. Thank you very much for the help.

**Comment by henrytao-me** [comment]
I pushed my commit. Please check and adjust delay time depending on your need. However, this is just a workaround for now until I find a better solution to calculate scrollingOffset in RecyclerView.

**Comment by henrytao-me** [comment]
Hi @arberg 

Let me know if v1.0.0 can fix this issue.

**Comment by arberg** [comment]
Hi Henry, 

Thanks, scrolling is great. I PM'ed you with minor problem. I noticed the buttons are sticky, and this listener gets called with 1.0 until too late it gets called with <1

```
    vSmoothCollapsingToolbarLayout.setOnOffsetChangedListener(new SmoothCollapsingToolbarLayout.OnOffsetChangedListener() {
        @Override
        public void onOffsetChanged(float ratio) {
            // Enable this to get a title shown when toolbar is collapsed.
            Log.i(TAG, "ratio=" + ratio);
            setTextOpacity(ratio > 0.5 ? 0 : 1 - ratio * 2);
        }
    });
```

Best Alex

**Comment by henrytao-me** [comment]
Hi @arberg 

I think I should close this ticket. 

Best, 
Henry

**Comment by arberg** [comment]
Sounds good, Thank you for the help. Just for others to know, the scrolling problem mentioned is also in the native google appbar layout and is a minor issue with regards to look and feel, so its not worth the effort for Henry to bugfix more of google code, I think.

Thank you for the help, Best Alex
