### ISSUE TITLE
Collapsing too early in Smooth ViewPager Parallax

### ISSUE THREAD

**Issue by kuhnp** [henrytao-me/smooth-app-bar-layout#56]
In the Smooth ViewPager Parallax example, the image starts fading very early. Is there any workaround to modify the offset that triggers the toolbar to collapse. The default value seems to be 2 times the size of the toolbar.

**Comment by henrytao-me** [comment]
Hi @kuhnp 

I am not sure about it. I haven't tried it. Did you look up on stackoverflow?
