### ISSUE TITLE
Possibilty to initially expand parallax appbarlayout to specific offset smaller than ImageView size

### ISSUE THREAD

**Issue by borgwald** [henrytao-me/smooth-app-bar-layout#60]
Hello,

i am trying to not fully expand my smoothappbarlayout. reason: my imageview inside collapsingtoolbarlayout can contain full sized images in portraitmode and i want to expand my smoothappbarlayout max half size of screen, maintainig the ability to expand further until the whole image is visible.

i tried it with Appbarlayout.Behavior: 

``` java
CoordinatorLayout.LayoutParams params = (CoordinatorLayout.LayoutParams) getAppBarLayout().getLayoutParams();
AppBarLayout.Behavior behavior = new AppBarLayout.Behavior();
behavior.setTopAndBottomOffset(0);
behavior.onNestedPreScroll(getCoordinatorLayout(), getAppBarLayout(), null, 0, getOffset(), new int[2]);
params.setBehavior(behavior);
getAppBarLayout().setLayoutParams(params);
```

this does expand my smoothappbarlayout only to the specified offset, but it also breaks overall scrolling behavior with smoothappbarlayout + collapsingtoolbarlayout + recyclerview

for better understanding: whats app is using a similar layout in their profileoverview of other users.

**Comment by henrytao-me** [comment]
Hi @borgwald 

I looked into WhatsApp profile style, I am not sure you are asking about cover animation or title/subtitle animation but overall, we can easily achieve this style with SmoothAppBarLayout and SmoothCollapsingToolbarLayout. 

I can make an example this weekend and ping you when it's ready. 

Cheers, 
Henry

**Comment by borgwald** [comment]
hello henry. 

when you look at whatsapp into the detail of a user, at the initial start of the detailactivity the toolbar is not expanded to the full imagesize. this is what i want to achieve. when you scroll down in whatsapp, the toolbar expands a little more until the whole image is visible. i dont have a good startingpoint on how to achieve this with smoothappbarlayout.

**Comment by henrytao-me** [comment]
Oh. I see what you mean. For that kind of style, I can make it work with ScrollView. Making it work with RecyclerView (with Async loading) is kind of tricky. What's your need right now? ScrollView with pre-design item or RecyclerView with async loading items?

**Comment by borgwald** [comment]
hello henry,

first of all thanks for your reply and efforts.

i am using a recyclerview in my layout.

**Comment by henrytao-me** [comment]
;). I found that our needs are always more than existing apps from BigCorp. But that makes things are more interesting. Let me work on it this weekend. Thanks for your consideration to use this library. 

Cheers, 
Henry

**Comment by borgwald** [comment]
Hello Henry,

did you have any Updates on this?

**Comment by henrytao-me** [comment]
Hi @borgwald 

Please upgrade to 23.2.1.2 and check `PreScroll` example. Note: Use [Utils.initPreScroll](https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/smooth-app-bar-layout%2Fsrc%2Fmain%2Fjava%2Fme%2Fhenrytao%2Fsmoothappbarlayout%2Fbase%2FUtils.java#L51)
