### ISSUE TITLE
Title displays ellipsis instead of full text in collapsed state

### ISSUE THREAD

**Issue by llpj** [henrytao-me/smooth-app-bar-layout#63]
If we use a long title it shows ellipsis in expanded state which is normal, but in collapsed state it should show full text as in standard coordinator layout

**Comment by henrytao-me** [comment]
Got it. Thanks for your report. Text collapsing will be fixed in up coming release. (soon)

**Comment by llpj** [comment]
Thanks! This look fixed. Where can I see the related change ? 
It does not seem to work for me when I use my own style.

**Comment by henrytao-me** [comment]
It fixed due to hug refactor. I don't think I can show you the change. ;)

**Comment by llpj** [comment]
Well,  thank you very much. I will find out anyway, sooner or later . ; )
