### ISSUE TITLE
RecyclerView scroll bug when swiping between tabs with Smooth ViewPager Parallax

### ISSUE THREAD

**Issue by bkolarov** [henrytao-me/smooth-app-bar-layout#68]
I noticed a bug, occurring also in the sample app. Lets say I have two tabs in a ViewPager with RecyclerViews. I scroll the first one to the bottom. Then I swipe. Then I scroll the second one to the bottom. Swipe back to the first one. Here if I try to scroll up (to scroll to the top) the RecyclerView doesn't move, but the collapsing toolbar is moving instead. In this case the RecyclerView should move first and handle the gesture and when it reaches it's top, then the collapsing bar should expand. 

Here I uploaded a video to give you a better idea of what is happening: https://www.youtube.com/watch?v=PywDGfZYTis

P.s: By the way good job with the library. I think it is the best I found so far.

**Comment by henrytao-me** [comment]
Hi @bkolarov 

I got what you mean. It's tricky to make ViewPager work perfectly with SmoothAppBar v0.x. I am refactoring the core library in v1.x. The fix for ViewPager is coming soon. I will let you now when it's ready. 

Thanks, 
Henry

**Comment by bkolarov** [comment]
Thank you for your fast reply. I'm looking forward to your updates. Meanwhile I'll let you know if we find a fix at work for that issue.

Good luck!

**Comment by henrytao-me** [comment]
Hi @bkolarov 

Please check out new version 1.0.3. It's fixed. 

Thanks!

**Comment by bkolarov** [comment]
I updated the project with the new version of your library. It is working properly now. Thank you!!
