### ISSUE TITLE
Dynamic AppBar Height

### ISSUE THREAD

**Issue by lishiyo** [henrytao-me/smooth-app-bar-layout#74]
Hi there! Thanks so much for making this. I was wondering, is there a way to support variable/dynamic appbarlayout heights, where my appbar wraps a placeholder fragment that when swapped can end up any height? 

```
<me.henrytao.smoothappbarlayout.SmoothAppBarLayout
        android:id="@+id/appbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:minHeight="50dp">
            <!-- Header placeholder -->
            <FrameLayout
                android:id="@+id/header_fragment_placeholder"
                app:layout_scrollFlags="scroll"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />
</me.henrytao.smoothappbarlayout.SmoothAppBarLayout>
// ...
<ViewPager />
```

^^My xml. In your examples it seems that `SmoothAppBarLayout` is a fixed height, rather than `wrap_content`. I set a minimum height as I'm using a viewpager, but the recyclerviews in the viewpager are being cropped at the top - it's clear the `SmoothAppBarLayout` height doesn't include the instantiated header fragment height. Is it possible to do so?

**Comment by henrytao-me** [comment]
Hi @lishiyo 

Please post the whole layout file, so that I can get more idea about what you want to do. What version of SmoothAppBarLayout are you using?

**Comment by lishiyo** [comment]
I'm using the latest version - `1.0.3` I believe. My layout file looks like -

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    android:id="@+id/root_blog_activity_container"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v4.view.ViewPager
        android:id="@+id/view_pager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:overScrollMode="never" />

    <me.henrytao.smoothappbarlayout.SmoothAppBarLayout
        android:id="@+id/appbar"
        android:minHeight="@dimen/tabs_bar_indicator_height"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

            <FrameLayout
                android:id="@+id/header_fragment_placeholder"
                app:layout_scrollFlags="scroll"
                android:layout_gravity="top"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

            <android.support.design.widget.TabLayout
                android:id="@+id/sliding_tabs"
                app:layout_scrollFlags="scroll|exitUntilCollapsed|enterAlways"
                android:layout_width="match_parent"
                android:layout_height="@dimen/tabs_bar_height"
                android:layout_gravity="bottom"
                android:visibility="invisible"
                android:minHeight="@dimen/tabs_bar_indicator_height"
                app:tabGravity="fill"
                app:tabMode="fixed" />

    </me.henrytao.smoothappbarlayout.SmoothAppBarLayout>

</android.support.design.widget.CoordinatorLayout>
```

In my activity's `onCreate`, I instantiate a new `HeaderFragment` which inflates another layout (the description, avatar, image etc) and `add` it to `R.id.header_fragment_placeholder`. 

I tried attaching a `ViewTreeObserver.OnGlobalLayoutListener` to the SmoothAppBarLayout and in its listener call `findViewById(R.id.root_blog_activity_container).requestLayout()`, but that didn't work unfortunately (viewpager top still cut off).

**Comment by henrytao-me** [comment]
Hi @lishiyo 

Below are few comments on your layout: 
- Set `layout_scrollFlags` in TabLayout is not a right approach. 
- If you use ViewPager, you should define `minHeight` for `SmoothAppBarLayout`. Check out some important notes here https://github.com/henrytao-me/smooth-app-bar-layout/wiki#important-notes
- `exitUntilCollapsed` and `enterAlways` are not a right combination. 

Try out my sample here https://github.com/henrytao-me/smooth-app-bar-layout/tree/issue-74 (`SmoothViewPagerActivity.java` and `activity_smooth_view_pager.xml`)

**Comment by lishiyo** [comment]
Hi @henrytao-me, I've tried out the sample and updated my layout:

```
<?xml version="1.0" encoding="utf-8"?>

<android.support.design.widget.CoordinatorLayout
    android:id="@+id/root_blog_activity_container"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v4.view.ViewPager
        android:id="@+id/view_pager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:overScrollMode="never" />

    <me.henrytao.smoothappbarlayout.SmoothAppBarLayout
        android:id="@+id/appbar"
        android:minHeight="@dimen/tabs_bar_indicator_height"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

            <!-- Header placeholder for BlogHeaderFragment -->
            <FrameLayout
                android:id="@+id/header_fragment_placeholder"
                app:layout_scrollFlags="scroll"
                android:layout_gravity="top"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

            <android.support.design.widget.TabLayout
                android:id="@+id/sliding_tabs"
                android:layout_width="match_parent"
                android:layout_height="@dimen/tabs_bar_height"
                android:layout_gravity="bottom"
                android:visibility="invisible"
                android:minHeight="@dimen/tabs_bar_indicator_height"
                app:tabGravity="fill"
                app:tabMode="fixed" />

    </me.henrytao.smoothappbarlayout.SmoothAppBarLayout>

</android.support.design.widget.CoordinatorLayout>
```

but the issue I think is that the header fragment is added into the appbarlayout _after_ `SmoothAppBarLayout.Behavior` has measured offset, so the viewpager's measurements are wrong.

**Comment by henrytao-me** [comment]
Hi @lishiyo 

I don't think delay adding header fragment causes any problem. 

I modified the code like below. After 3s, it still worked correctly. 

``` java
    new Handler().postDelayed(new Runnable() {
      @Override
      public void run() {
        getSupportFragmentManager()
            .beginTransaction()
            .replace(R.id.header_holder_fragment, mHeaderHolderFragment)
            .commit();
      }
    }, 3000);
```

Would you mind to record a video to show the issue?

**Comment by lishiyo** [comment]
Sure! Here's a gif: https://media.giphy.com/media/1x7qw0P0Fw6vm/giphy.gif

That gif's a bit quick, but you can see how the inserted fragment "covers" the viewpager:
<img src=https://cloud.githubusercontent.com/assets/7489058/13093434/49eb7052-d4d3-11e5-86d9-474493784985.png width=210>

This is the code I added to get that gif, using your `SmoothViewPagerActivity` sample: https://gist.github.com/lishiyo/4c53066e1b348f7371b3

# 

Btw, I also tried adding `app:layout_behavior="@string/appbar_scrolling_view_behavior"` to the ViewPager as `AppBarLayout$ScrollingViewBehavior` has an `updateOffset` method that seems specifically to make sure the viewpager is always below the appbar (comment says "Offset the child so that it is below the app-bar (with any overlap)". With that added, the viewpager is no longer covered but the gap is too large:
<img src=https://cloud.githubusercontent.com/assets/7489058/13093143/a0d73556-d4d1-11e5-80ff-acd7ef532bc7.png width=210>

**Comment by henrytao-me** [comment]
I see what you mean. IMO, it's not a best practice to change header height on the fly like that. If you really want to change it, here are my suggestions: 
- SmoothAppBarLayout uses HeaderView for both ScrollableView for each PagerItem (RecyclerView or NestedScrollView) and PlaceHolderView outside ScrollableView (HelloWorld view + Toolbar + TabLayout). Those views must have the same height. If you change PlaceHolderView height, you should change HeaderView height too. This is why your content is cut off (your gif). 
- SmoothAppBarLayout requires to remove `app:layout_behavior="@string/appbar_scrolling_view_behavior"`. Please don't use default scrolling behavior. It won't work.

**Comment by juliooa** [comment]
Hi @henrytao-me ! Thanks for your awesome library.

I got the same problem from this issue, I'm trying to add a custom view in the header. And when the user scroll I want a parallax effect.
The problem is that the viewpager content (recycleviews) get cut and hidden behind the tabs.

<img width="410" alt="screen shot 2016-02-17 at 8 23 32 pm" src="https://cloud.githubusercontent.com/assets/1221345/13128468/af9869d2-d5b4-11e5-9f5c-69c4b471b0f6.png">

Here is my layout, I try to modify your activity_smooth_view_pager.xml:

``` xml
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  android:layout_width="match_parent"
  android:layout_height="match_parent">

  <me.henrytao.smoothappbarlayout.SmoothAppBarLayout
    android:id="@+id/smooth_app_bar_layout"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:minHeight="42dp">

    <android.support.design.widget.CollapsingToolbarLayout
        android:id="@+id/collapsing_toolbar_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_scrollFlags="scroll|exitUntilCollapsed">

      <android.support.v7.widget.Toolbar
          android:id="@+id/toolbar"
          app:layout_collapseMode="pin"
          app:navigationIcon="@drawable/ic_toolbar_arrow_back"
          style="@style/AppStyle.MdToolbar"
          android:visibility="gone"/>

      <me.henrytao.smoothappbarlayout.SmoothCollapsingToolbarLayout
          android:layout_width="match_parent"
          android:layout_height="wrap_content"
          android:gravity="left|center_vertical"
          android:minHeight="42dp"
          app:sctl_subtitle_id="@+id/subtitle"
          app:sctl_title_id="@+id/title"
          app:layout_collapseMode="parallax">


        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="180dp"
            android:gravity="center_horizontal|center_vertical"
            android:orientation="vertical">

          <TextView
              android:id="@+id/title"
              android:text="Title"
              android:layout_width="match_parent"
              android:layout_height="wrap_content"
              android:gravity="center_horizontal|center_vertical" />

          <TextView
              android:id="@+id/subtitle"
              android:text="Subtitle"
              android:layout_width="match_parent"
              android:layout_height="wrap_content"
              android:gravity="center_horizontal|center_vertical"/>
        </LinearLayout>
      </me.henrytao.smoothappbarlayout.SmoothCollapsingToolbarLayout>
    </android.support.design.widget.CollapsingToolbarLayout>

    <android.support.design.widget.TabLayout
      android:id="@+id/tab_layout"
      android:layout_width="match_parent"
      android:layout_height="wrap_content" />
  </me.henrytao.smoothappbarlayout.SmoothAppBarLayout>

    <android.support.v4.view.ViewPager
        android:id="@+id/view_pager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clipToPadding="false"/>
</android.support.design.widget.CoordinatorLayout>
```

**Comment by juliooa** [comment]
ok this is weird, if I invert the order and put the viewpager first, this happened 
<img width="408" alt="screen shot 2016-02-17 at 8 31 53 pm" src="https://cloud.githubusercontent.com/assets/1221345/13128603/b95b5492-d5b5-11e5-8ed8-5b31f82206d8.png">

**Comment by henrytao-me** [comment]
Hi @juliooa,

As I mentioned above, each viewpager item header (either paddingTop of NestedScrollView or item 0 of RecyclerView) should have the same height with custom header. 

If you forked my repo, can you share it to me? So that I can check and fix your sample.

**Comment by juliooa** [comment]
hi! @henrytao-me, thanks for the quick response, yes I upload the sample here:
https://github.com/juliooa/smooth-app-bar-layout/tree/feature/custom-view-header

**Comment by henrytao-me** [comment]
Hi @juliooa 

Please add me as a collaborator to your repo. I fixed your spacing issue and wanna send PR for you to review. 

Thanks, 
Henry

**Comment by juliooa** [comment]
hi @henrytao-me, great! done

**Comment by henrytao-me** [comment]
Cool. Please check out my diffs here. https://github.com/juliooa/smooth-app-bar-layout/pull/1/files

**Comment by henrytao-me** [comment]
How's about you @lishiyo? You can check out @juliooa code and take a look too.

**Comment by juliooa** [comment]
you are the man @henrytao-me , works like a charm, and smooth as silk. I see how you fix it, thanks man.

I noticed something, If I scroll a recyclerview to a point where half of the custom view is seen, then swipe to another tab, and move the scroll in this new tab there is a jump on the scroll. Anyway I think this is for other issue.

**Comment by lishiyo** [comment]
Thanks for the sample @juliooa and @henrytao-me :D I went with a separate approach because I do not know what the header's height will be within the xml, so I can't set `200dp` for example. Instead I created a viewholder subclass that would force the header viewholder to a certain height:

```
final HeaderHolder holder = new DynamicHeaderHolder(layoutInflater, viewGroup, R.layout.item_pager_header_spacing, getAppBarHeight()); // height passed from activity

public static class DynamicHeaderHolder extends BaseAdapter.HeaderHolder {
    public DynamicHeaderHolder(LayoutInflater inflater, ViewGroup parent, @LayoutRes int layoutId, int visibleHeaderHeight) {
      super(inflater, parent, layoutId);
      if (appBarLayout != null) {
        getItemView().getLayoutParams().height = visibleHeaderHeight;
      }
    }
  }
```

Mostly works, except when in the halfway down the header and then swiping to another tab the header will cover it again, so have to use something like `AppBarLayout.onOffsetChanged()` to adjust the visible header height and set that.

Thanks for your help!

**Comment by henrytao-me** [comment]
Hi @lishiyo 

It's sound good. Let me know if you need more help.

**Comment by bbincybbaby** [comment]
@lishiyo can u explain it more detail
