### ISSUE TITLE
collapsingtoolbar with viewpager

### ISSUE THREAD

**Issue by lulumeya** [henrytao-me/smooth-app-bar-layout#76]
Thank you very much guys you saved my day.

I have questions

I want to implement ui like "scroll exituntilcollapse" but I want to use viewpager instead of recyclerview, How can I achieve that?

and another, in the sample, viewpager exituntilcollapse, when I move to second tab dog which has recyclerview instead of nestedscrollview, scrolling behavior looks like to have snap attribute. How can I avoid snap?

**Comment by henrytao-me** [comment]
Hi @lulumeya 

I guess you want to have Parallax ViewPager example. Please check out this forked branch (check diff). https://github.com/juliooa/smooth-app-bar-layout/tree/feature/custom-view-header

I will update this example in my repo later. 

About snap issue, can you record a video to illustrate the issue?

**Comment by lulumeya** [comment]
I'll check the fork you send me, Thank you very much.

the issue I sad is my mistake, sorry.

2016년 2월 18일 (목) 오전 11:43, Henry Tao notifications@github.com님이 작성:

**Comment by lulumeya** [comment]
Henry, Help me again please.

I like to use layout of this
https://github.com/henrytao-me/smooth-app-bar-layout#smoothcollapsingtoolbarlayout-example

I could change recyclerview to viewpager in this sample, but I can add
TabLayout to SmoothAppBarLayout because SmoothAppBarLayout ignores
TabLayout in it.

When I change SmoothAppBarLayout's height to wrap_content, it behave weird.
Is there any quick fix for this?

2016년 2월 18일 (목) 오후 12:02, 이학수 lulumeya@gmail.com님이 작성:

**Comment by henrytao-me** [comment]
Give me an hour. I will get back after lunch. ;)

**Comment by henrytao-me** [comment]
Hi @lulumeya 

Please remember to set `minHeight` for `SmoothAppBarLayout` when using ViewPager. Check out some importance notes here https://github.com/henrytao-me/smooth-app-bar-layout/wiki

**Comment by lulumeya** [comment]
Yes I set minHeight for SmoothAppBarLayout.

The ViewPager is not problem, I want to add TabLayout for
SmoothAppBarLayout which has CollapsingToolBarLayout which has
SmoothCollapsingToolBarLayout...

<CoordinatorLayout>
   <ViewPager/>
   <SmoothAppBarLayout>
      <CollapsingToolBarLayout>
         <SmoothCollapsingToolBarLayout>
            ...some views
         </SmoothCollapsingToolBarLayout>
      </CollapsingToolBarLayout>
      <TabLayout/>
   </SmoothAppBarLayout>
<CoordinatorLayout>

looks like this...

2016년 2월 18일 (목) 오후 3:25, Henry Tao notifications@github.com님이 작성:

**Comment by henrytao-me** [comment]
Hi @lulumeya 

`SmoothCollapsingToolBarLayout` worked in previous version (0.x). It needs to improve a bit in order to work with v1.x. Please don't use it for now. Here is the improvement's request https://github.com/henrytao-me/smooth-app-bar-layout/issues/26

I will send you an example about ViewPager + CollapsingToolbarLayout + Parallax shortly. 

Cheers, 
Henry

**Comment by henrytao-me** [comment]
Yo @lulumeya 

Check out ViewPager Parallax example here. 
[activity_smooth_view_pager_parallax_exit_util_collapsed.xml](https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/sample%2Fsrc%2Fmain%2Fres%2Flayout%2Factivity_smooth_view_pager_parallax_exit_util_collapsed.xml) and [SmoothViewPagerParallaxExitUntilCollapsedActivity.java](https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/sample%2Fsrc%2Fmain%2Fjava%2Fme%2Fhenrytao%2Fsmoothappbarlayoutdemo%2Factivity%2FSmoothViewPagerParallaxExitUntilCollapsedActivity.java)

**Comment by lulumeya** [comment]
Oh great Thanks! I ll check it!

**Comment by henrytao-me** [comment]
I will close this issue. Let me know if you need more help @lulumeya

**Comment by lulumeya** [comment]
Yes, Thank you for helping me.

2016년 2월 20일 (토) 오후 5:51, Henry Tao notifications@github.com님이 작성:
