### ISSUE TITLE
How to use it with SwipeRefreshLayout?

### ISSUE THREAD

**Issue by kvart714** [henrytao-me/smooth-app-bar-layout#82]
Thanks, it solved all my problems with scrolling, CollapsingToolbarLayout and ViewPager!

But there is a new problem and I do not know how to solve it:

I have to put  header in the NestedScrollView, but NestedScrollView is inside SwipeRefreshLayout and it is not visible because it is covered under AppBar.

If I put header before SwipeRefreshLayout, then NestedScrollView is scroll simultaneously with AppBar.

**Comment by henrytao-me** [comment]
Can you post your layout here?

**Comment by henrytao-me** [comment]
I got what you mean. You need to define these methods `getActionBarSize()` and `getHeaderHeight()`, then use below code: 

```
  int actionBarSize = getActionBarSize();
  int progressViewStart = getHeaderHeight();
  int progressViewEnd = progressViewStart + (int) (actionBarSize * 1.5f);
  vSwipeRefreshLayout.setProgressViewOffset(true, progressViewStart, progressViewEnd);
```

**Comment by kvart714** [comment]
Thank you, it works :)

**Comment by henrytao-me** [comment]
Sweet. Happy coding!
