### ISSUE TITLE
Choppy SmoothAppBar behavior when switching between tabs and swiping up or down

### ISSUE THREAD

**Issue by FelisManulus** [henrytao-me/smooth-app-bar-layout#93]
Greetings. 
I've noticed an issue when switching between fragments in 'ViewPager Parallax demo' and swiping up or down the scrollable area a bit. The issue persists in my project too.

How it should be (first switch between tabs is ok): https://youtu.be/rsyk0Gwu4Gs
How it is now (second etc. switches): https://youtu.be/jSVCQzXvO4Y

P. S. It would be also great to add expanding animation to SmoothAppBar when tabs are switched from scrollable to non-scrollable **OR** leave it the same height as on the previous tab. It expands now instantly which is not a very pleasant UX.
Here is what I'm talking about: https://youtu.be/XH-2mxwombw

**Comment by henrytao-me** [comment]
Hi @FelisManulus 

Thanks for your report. This is known-issue and I am improving it. If you think SmoothAppBarLayout is better than AppBarLayout in your use-case, please don't hesitate to give it a try. 

Thanks, 
Henry

**Comment by FelisManulus** [comment]
Greetings, the issue still exists in 'ViewPager Parallax demo' (new versrion 21.04.16) on my device.
Maybe there's another demo where it is fixed?
I have to use another library now but I'd rather use yours in case it gets fixed.
Thanks.
