### ISSUE TITLE
Broken scrolling of Smoothappbarlayout with newest Library

### ISSUE THREAD

**Issue by borgwald** [henrytao-me/smooth-app-bar-layout#94]
Hello Henry,

i have updated the Design-Library to version 23.2.1. With newest DesignLibrary and older Version of your Library i had no Problems. But after updating to your newest Library, scrolling of Smoothappbarlayout is broken.

My Layout: 

``` java
<android.support.design.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/coordinatorLayout">
        <FrameLayout
            android:id="@+id/mdContent"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>
        <me.henrytao.smoothappbarlayout.SmoothAppBarLayout
            android:id="@+id/appbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">
                <android.support.v7.widget.Toolbar
                    android:id="@+id/toolbar"
                    android:layout_width="match_parent"
                    android:layout_height="?attr/actionBarSize"
                    android:background="@color/primary"
                    android:theme="@style/ToolbarDarkOverflow"
                    app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
                    app:layout_scrollFlags="scroll|enterAlways|enterAlwaysCollapsed">
                      <TextView
                         android:id="@+id/toolbar_title"
                         android:layout_width="wrap_content"
                         android:layout_height="wrap_content"
                         android:layout_gravity="center_vertical"
                         android:singleLine="true"
                         android:textColor="@android:color/white"
                         android:textSize="16sp"
                         android:textStyle="normal" />
                </android.support.v7.widget.Toolbar>
                <android.support.v7.widget.Toolbar
                     android:id="@+id/search_toolbar1"
                     android:layout_width="match_parent"
                     android:layout_height="?attr/actionBarSize"
                     android:background="@color/primary"
                     android:paddingLeft="10dp"
                     android:paddingRight="10dp"
                     android:gravity="center"
                     android:theme="@style/ToolbarDarkOverflow">
                     <android.support.v7.widget.SearchView
                         android:layout_width="wrap_content"
                         android:layout_height="wrap_content"
                         android:id="@+id/search_view1"
                         app:queryHint="Search..."/>
              </android.support.v7.widget.Toolbar>
        </me.henrytao.smoothappbarlayout.SmoothAppBarLayout>
    </android.support.design.widget.CoordinatorLayout>
```

Problem:

The first FrameLayout is a container for a Fragment with Recyclerview. The Recyclerview has a Header with the height of 2*toolbar height because i use a second toolbar below the first.

When scrolling the Recyclerview the first Toolbar scrolls like it should out of the Screen. But the second Toolbar scrolls out of the screen too and then starts flickering on top of the screen while scrolling. Normal behvior should be that the second Toolbar stays on Top of the Screen. (Quick return pattern)

Like i said with an older Version of your Library there doesn't exist this Problem.

**Comment by henrytao-me** [comment]
Hi @borgwald 

I am checking it now.

**Comment by henrytao-me** [comment]
Hi @borgwald 

Using 2 Toolbar looks weird to me. Can you post a video or screenshot about what your expectation? So that I can give a proper design.

Thanks, 
Henry

**Comment by borgwald** [comment]
Hello Henry,

it's not an issue with two toolbars. I have tested it with a TabLayout and only one Toolbar also. The TabLayout also scrolls off the screen. Reverting back to older Library everything works as expected.

**Comment by borgwald** [comment]
This is with new Library. As you can see the TabLayout scrolls off the screen:

![ezgif-593512791](https://cloud.githubusercontent.com/assets/2222317/14580634/f43df596-03d3-11e6-8844-569f64115658.gif)

And the following is with older Library. The TabLayout scrolls as expected. No changes in Code. Only changed to older Library:

![ezgif-3394553392](https://cloud.githubusercontent.com/assets/2222317/14580640/41c4ecf2-03d4-11e6-9532-f5d9e5e43efd.gif)

**Comment by henrytao-me** [comment]
Hi @borgwald 

If you want to implement that type of AppBarLayout, I prefer to use original AppBarLayout implementation which you can find in my sample app too. Because with original AppBarLayout, there are no need for you to setup HeaderView for each tab fragment. 

If you want to do more fancy animation like: exitUntilCollapse and quickReturn for ViewPager, then try SmoothAppBarLayout. 

I hope it will help. 

Cheers, 
Henry

**Comment by borgwald** [comment]
its only an example. i have these problems even if i dont't use a viewpager and tablayout as mentioned. Normal behavior is that only the toolbar should scroll off. The question is why does it work with an older Library of Smoothappbar and not with the newest one...

i am not sure if you understand what i mean..

**Comment by borgwald** [comment]
for better understanding

this is an example with your old Library and without Viewpager:

![ezgif-950987267](https://cloud.githubusercontent.com/assets/2222317/14581289/6786cc98-03e9-11e6-9923-be7f5636a16e.gif)

the searchtoolbar stays on top. This is expected behavior.

But with your newest Library the searchtoolbar scrolls out of the screen.

I would like to use your newest Version because of Utils.intPreScroll implementation. (#60) 
But i can't because of this issue.

**Comment by henrytao-me** [comment]
Hi @borgwald 

What the old version number are you using (the one works normally)? Utils.initPreScroll is a static method. You probably can copy to your project unless there is a big different between old working version and new broken version (due to refactor and improvement).

**Comment by borgwald** [comment]
Hello Henry,

i am using version 0.2.3. unfortunately the newer versions have major changes in syncOffset Method. i.e.
newer versions use syncOffset(appbarlayout, newOffset) which is not included in the old version that works for me.
