### ISSUE TITLE
StackOverFlowError

### ISSUE THREAD

**Issue by FabianShallari** [henrytao-me/smooth-app-bar-layout#96]
Hi @henrytao-me . When using SmoothAppBarLayout with ViewPager I'm getting this issue: 
`java.lang.StackOverflowError
    at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:652)
    at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
    at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:652)
    at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)
    at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:652)
    at me.henrytao.smoothappbarlayout.BaseBehavior.onMeasureChild(BaseBehavior.java:80)`

By the stack trace I think it has to do with something that is recursively calling back and forth.
what do you think?

**Comment by FabianShallari** [comment]
Also the ViewPager Quick Return on the sample app crashes when building and compiling from master

**Comment by FabianShallari** [comment]
the stackoverflow error seems to happen only with supportLib 23.3.0.

**Comment by kjw1801** [comment]
I also same issues.

I think it seems that is not supported version.

compile 'com.android.support:appcompat-v7:23.3.0'
compile 'com.android.support:design:23.3.0'

**Comment by henrytao-me** [comment]
Let me try

**Comment by henrytao-me** [comment]
Hi @FabianShallari and @kjw1801 

Can you provide more context when it's crashed. Ex: device name, version...

I just tested on v23.3.0 and master build. It works normally. 

Thanks, 
Henry

**Comment by henrytao-me** [comment]
Any updates on your sides?

**Comment by FabianShallari** [comment]
Will try to rebuild master in a few days and notify you again. Thanks for the commitment!

**Comment by kjw1801** [comment]
I am currently using without any problems. Thank you.

**Comment by henrytao-me** [comment]
Thanks @kjw1801

**Comment by sudansh** [comment]
This issue is still not fixed. This persists even in 23.4.0

**Comment by henrytao-me** [comment]
Hi @sudansh 

How did you setup ViewPager? I am using 23.3.0. It's okie. Weird?

**Comment by steffandroid** [comment]
I'm also getting this issue, on a Moto X (2014) running Android 6.0, using support library version 23.4.0.

The problem is not present if I revert the support library to 23.1.1.

**Comment by henrytao-me** [comment]
I see. Working on it now.

**Comment by steffandroid** [comment]
Ah, sorry, I've just realised I was compiling an old version of this library. It actually seems fine on the latest version.

**Comment by henrytao-me** [comment]
Sweet. :D Thanks for your confirmation. I am also checking the code to see if there are any issues.

**Comment by dkshin** [comment]
@henrytao-me

1.
compile 'com.android.support:appcompat-v7:23.1.1'
compile 'com.android.support:design:23.1.1' 
-> working

2.
only compile 'com.android.support:appcompat-v7:23.3.0'
-> working

3.
only compile 'com.android.support:appcompat-v7:23.4.0'
-> working

4.
compile 'com.android.support:appcompat-v7:23.3.0'
compile 'com.android.support:design:23.3.0'
->  same issues

5.
compile 'com.android.support:appcompat-v7:23.3.0'
compile 'com.android.support:design:23.3.0'
-> same issues

**Comment by henrytao-me** [comment]
@dkshin 

Can you send me your full grade file?

**Comment by dkshin** [comment]
@henrytao-me 

Check your email(hi@henrytao.me)! :-)

**Comment by bicos** [comment]
@dkshin, @henrytao-me I found that if CoordinatorLayout's child's param's height is WRAP_CONTENT, it makes stackoverflow error. so, instead of WRAP_CONTENT, I fixed SmoothAppBarLayout's height, stackoverflow error is gone. please check out AppBarLayout onMeasureChild method!

**Comment by henrytao-me** [comment]
Interesting. Let me check. Thanks @bicos

**Comment by henrytao-me** [comment]
If you use version `3.0.0` with support design `23.3.0`, it will be fine.

**Comment by nenick** [comment]
This can be reproduced with your sample app. Change the dependency to your release `23.2.1`.

from 

```
compile(project(":smooth-app-bar-layout")) {
    exclude group: "com.android.support"
}
```

to

```
compile ("me.henrytao:smooth-app-bar-layout:23.2.1") {
    exclude group: "com.android.support"
}
```

Clean install the sample app and start the scroll sample on the right (left one still works). -> crash

Looks like when we use the sources all works fine, but when using the dependency then we get this crash. The same behaviour occurs when I use the code revision from release `23.2.1` and using a dependency instead of project sources.

What do you mean with using version `3.0.0`?

**Comment by henrytao-me** [comment]
I saw it. For now, it works normally on `me.henrytao:smooth-app-bar-layout:3.0.0` and `com.android.support:design:23.3.0`. 

What AppCompat and SupportDesign version are you using?

**Comment by nenick** [comment]
Thanks `3.0.0` does fix the issue. I'm useing SupportDesign version `23.4.0`. Bad that I found no release notes about it.

**Comment by henrytao-me** [comment]
Sorry. It's my bad.

**Comment by henrytao-me** [comment]
Checkout all supported versions here. Thanks. The version of SupportDesign, AppCompat and SmoothAppBarLayout should be the same. Otherwise, you will get this issue. 
https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/CHANGES.md
