### ISSUE TITLE
Sometimes get max offset when scrolling to top.

### ISSUE THREAD

**Issue by showang** [henrytao-me/smooth-app-bar-layout#98]
onCreateItemViewHolder: 0
onOffsetChanged: 0
onOffsetChanged: 0
onOffsetChanged: 0
onOffsetChanged: 0
onOffsetChanged: 168
onOffsetChanged: 168
onOffsetChanged: 101
onOffsetChanged: 101
onOffsetChanged: 41
onOffsetChanged: 41
onOffsetChanged: 0
onOffsetChanged: 0
onOffsetChanged: 0

This masks toolbar disappear for a while.

compile "me.henrytao:smooth-app-bar-layout:23.3.0"
compile 'com.android.support:support-v4:23.3.0'
compile 'com.android.support:appcompat-v7:23.3.0'
compile 'com.android.support:recyclerview-v7:23.3.0'

I using smooth-app-bar-layout with recyclerview in viewpager.

Same problem in ver 23.2.1.

**Comment by henrytao-me** [comment]
Hi @showang 

Can you provide more context of your example? Ex: appcompat version, smoothappbarlayout version, what type of appbar are you using, what device are you testing...

Thanks,
Henry

**Comment by showang** [comment]
This bug is fixed when i change to ver 23.2.1.

**Comment by showang** [comment]
After i test many times, this bug was occurred when recyclerview scroll to position 0. (most frequency)
But not be occurred every times.

**Comment by showang** [comment]
Another question, how to work with swipe-to-refresh-layout?

**Comment by henrytao-me** [comment]
Hi @showang 

Please check SwipeRefreshLayout example here. https://github.com/henrytao-me/smooth-app-bar-layout/blob/master/sample%2Fsrc%2Fmain%2Fjava%2Fme%2Fhenrytao%2Fsmoothappbarlayoutdemo%2Factivity%2FSmoothSwipeRefreshLayoutActivity.java

Regard to your issue, can you send me your layout file and screenshots?

**Comment by showang** [comment]
I found the root cause!!
RecyclerView has a bug that scroll offset might be wronged when using multiple view type.

**Comment by henrytao-me** [comment]
I tried multiple view type in my production app. It doesn't cause this issue. Weird.
